emoncms/emoncms

Modules/dashboard/Views/dashboard_menu.php

See ["dashboard -> "List view"-icon not visible"](http://openenergymonitor.org/emon/node/6389) forum thread.

Reinstate the dashboard list button

---

Modules/feed/Views/feedlist_view.php
Modules/input/Views/input_view.php
Modules/node/node_controller.php
Modules/node/node_view.php
Theme/menu_view.php
readme.md

To help future merges between branches.

Backport minor fixes on Master to Extended.

---

Modules/dashboard/Views/dashboard_list.php
Modules/dashboard/Views/js/widgets/vis/vis_render.js
Modules/feed/Views/feedlist_view.php
Modules/feed/feed_model.php
Modules/feed/feed_schema.php
Modules/input/Views/input_view.php
Modules/input/Views/process_info.js
Modules/input/input_controller.php
Modules/node/node_view.php
Modules/user/user_model.php
Modules/vis/multigraph_model.php
Modules/vis/vis_controller.php
Theme/emon.css
Theme/theme.php
locale.php

On Modules\feed\feed_model.php:  'Explicitly set decimal separator, in case current locale doesn't use a dot (MySQL expects always a dot, regardless of locale)' 
Was removed because of possible issues  with large numbers.
See: https://github.com/emoncms/emoncms/pull/304/files#diff-ef4a46a9ff8dd8d8cc90d51b3b0f3362R644
Fix was made to Modules\user\user_model.php API language is always EN.
This ensures all API post data (arduino firmware) follows english localization style.
See: https://github.com/emoncms/emoncms/pull/304/files#diff-3a8983b5e260461fe91544f3ff97de77R56

Backport of minor fixes on Extended to Master to simplify future merge.

---

docs/setup.md

http://openenergymonitor.org/emon/node/10450

minor corrections

---

Lib/flot/jquery.flot.touch.js

Allows to use touch for pan / zoom and simulate tap, double tap as mouse
clicks so other plugins can work as usual with a touch device.

Added tap double tap support for graphs.

---

Modules/input/Views/processlist.js

Issue described here http://openenergymonitor.org/emon/node/10539

 Fix unavailable interval selector for new feeds

---

Modules/dashboard/Views/loadwidgets.php
Modules/input/Views/processlist.js

Fix for issue related here https://github.com/emoncms/emoncms/issues/324

Fix feeds not available in processors with undefined engine

---

filelogger.logconfig.xml
logconfig.xml

Match line 96 ' $log4php_configPath = 'logconfig.xml';' in default.settings.php

Logging Fix

---

Modules/feed/engine/MysqlTimeSeries.php
Modules/feed/engine/PHPFina.php
Modules/feed/engine/PHPFiwa.php
Modules/feed/engine/PHPTimeSeries.php
Modules/feed/feed_model.php
Modules/input/Views/process_info.js
Modules/input/process_model.php
Modules/log/EmonLogger.php
docs/LinuxInstall.md
logconfig.xml

Refactored some code from 8.5 -> Instead of if (!is_numeric($lastvalue['time'])) in feed_model.php i fixed the reason it may not be.
Also some minor fix on getstartday function on process_model.php

Fix Min Max processors + Merge with 8.5 latest

---

Modules/user/user_model.php

See http://openenergymonitor.org/emon/node/10687

 	Change array initialisation to be compatible with PHP pre-5.4

---

Modules/feed/Views/feedlist_view.php
Modules/feed/engine/MysqlTimeSeries.php
Modules/user/login_block.php
Modules/user/rememberme_model.php
Modules/user/user_controller.php
Modules/user/user_model.php
Modules/user/user_schema.php
core.php
default.settings.php
index.php

Fix remember me.
Asks for login when needed.
Add support for apikey in "Authorization: Bearer THE_API_KEY_HERE" http
header per rfc6750.

EmonCMS | 9 RC | 2015.08.29

---

default.settings.php
index.php

If the $theme variable in settings.php is not "basic", it looks now for the path of the external theme (previously, it was ignored).

Support for external themes

---

Modules/user/login_block.php

I did not fixed incorrect logins in the previous pull request, and if the credentials were wrong the page would reload incorrectly. Sorry, my bad.

Fix incorrect logins

---

Modules/dashboard/dashboard_model.php
Modules/feed/feed_model.php
Modules/input/input_controller.php
Modules/input/input_model.php
Modules/input/que_input_controller.php
Modules/schedule/schedule_model.php
Modules/user/user_model.php
Modules/vis/multigraph_model.php
Modules/vis/vis_controller.php
index.php

- Fixed regex expressions to support utf-8 characters
- Fixed a security bug where the $tag parameter on input_mode.php was not being sanitized
- Set charset to utf-8 in the database connection
It should fix the issue #369

UTF-8 support

---

docs/LinuxInstall.md
docs/RaspberryPi.md
readme.md

Adds new Raspberry Pi installation guide.
Very much a team effort by several members, and has also been tested several times from scratch.

Installation guide for Raspberry Pi

---

Modules/dashboard/dashboard_model.php
Modules/feed/feed_model.php
Modules/input/input_controller.php
Modules/input/input_model.php
Modules/input/que_input_controller.php
Modules/schedule/schedule_model.php
Modules/user/user_model.php
Modules/vis/multigraph_model.php
Modules/vis/vis_controller.php

Sorry, completely my bad. I replaced \w with \p{N}\p{L} but forgot that \w actually takes underscores as well.

Fix bug that broke regexp with underscores

---

Modules/dashboard/widget/dewpoint/dewpoint_render.js
Modules/feed/Views/feedapi_view.php
Modules/feed/engine/MysqlTimeSeries.php
Modules/feed/feed_controller.php
Modules/feed/feed_model.php
Modules/input/input_controller.php
Modules/process/process_model.php
index.php

Add new widget : dewpoint.
Clean now unsupported functions feed->get by name.

 Emon CMS 9 RC2 | 2015.09.15

---

Modules/user/user_model.php

Is there any reason not to allow 3-character usernames?
Also passwords should probably be required to be longer than 4

Allow 3-character usernames

---

.gitignore
Modules/admin/admin_controller.php
Modules/admin/admin_main_view.php
Modules/device/Views/device.js
Modules/device/Views/device_api.php
Modules/device/Views/device_view.php
Modules/device/data/amig.json
Modules/device/data/example.json
Modules/device/device_controller.php
Modules/device/device_menu.php
Modules/device/device_model.php
Modules/device/device_schema.php
Modules/feed/engine/PHPFina.php
Modules/feed/engine/VirtualFeed.php
Modules/input/input_model.php
Modules/process/process_model.php
Modules/process/process_processlist.php
Modules/user/user_model.php
default.emonpi.settings.php
docs/RaspberryPi/Low-write-mode.md
docs/RaspberryPi/MQTT.md
docs/RaspberryPi/USB_HDD.md
docs/RaspberryPi/general.md
docs/RaspberryPi/install_Raspbian_Jessie.md
index.php
readme.md
scripts/mqtt_input

Bug fix on virtual feeds last time update
Added device module
Merge docs

EmonCMS 9.2 | 26.11.2015

---

Modules/feed/feed.js
Modules/input/Views/input.js
Modules/vis/visualisations/common/vis.helper.js
index.php

Merged contibuted fixes: tooltip  and input.js

EmonCMS 9.2 | 2015.11.27

---

Modules/user/login_block.php

Place \<div id="passwordresetmessage"\> outside \<div id="passwordresetblock"\> to keep result visible after submit

Change passwordresetmessage page location

---

Modules/dashboard/widget/jgauge/jgauge_render.js
Modules/dashboard/widget/jgauge2/jgauge2_render.js

Added min value support to jgauge and jgauge2 widgets.

EmonCMS 6.2 | 2015.12.05

---

Modules/feed/Views/feedlist_view.php
Modules/feed/engine/MysqlTimeSeries.php
Modules/feed/engine/VirtualFeed.php
Modules/vis/visualisations/multigraph/multigraph.js
index.php

Bugfixing on export virtual feeds data.

EmonCMS 9.2 | 2015.12.11

---

docs/RaspberryPi/readme.md

http://openenergymonitor.org/emon/node/11809
http://openenergymonitor.org/emon/node/11456

Added note to prompt user to set local emoncms url

---

Modules/user/user_model.php

Increase the maximum length of all passwords to 250 characters (enough for users but stops huge posts). https://github.com/emoncms/emoncms/issues/430

Increase maximum length of passwords to 250 chars

---

Modules/user/user_model.php

Typo in password reset mail

---

Modules/vis/Views/vis_main_view.php
Modules/vis/vis_object.php
Modules/vis/visualisations/stacked.php
Modules/vis/widget/vis_render.js

Adds colour configuration options to Stacked visualization

Stacked vis colors

---

Modules/vis/visualisations/timestoredaily.php

Fixes timestoredaily showing wrong value for present day

---

Lib/EmonLogger.php
Lib/email.php
Lib/tablejs/custom-table-fields.js
Lib/tablejs/table.js
Modules/user/user_model.php
Modules/vis/Views/vis_main_view.php
Modules/vis/vis_object.php
Modules/vis/visualisations/stacked.php
Modules/vis/visualisations/timestoredaily.php
Modules/vis/widget/vis_render.js
default.emonpi.settings.php
default.settings.php
index.php
scripts/export_montly_cron.php

Minor fixes
Remove of critical log level.
Merge of:
Stacked vis colors
Fixes timestoredaily showing wrong value for present day

EmonCMS 9.3 | 2016.01.16 

---

Lib/tablejs/table.js
default.emonpi.settings.php
default.settings.php
index.php

EmonCMS 9.3 | 2016.01.18

---

Modules/vis/visualisations/multigraph/multigraph.js
Modules/vis/visualisations/timecompare/timecompare.js

Addresses http://openenergymonitor.org/emon/node/12021

Bugfix to allow negative numbers on timecompare and multigraph

---

Lib/listjs/list.js
Modules/admin/admin_main_view.php

@exec('uname -a') wasn't working, and it's better to call native PHP functions

Fix uname and Gravatar URI

---

Modules/vis/visualisations/bargraph.php

Set hover text to 24h format

---

Modules/vis/vis_controller.php

Fixes PHP error in bargraph visualization

Proper handling of colour options in widgets

---

core.php

To allow symlinked modules e.g. backup module https://github.com/emoncms/backup

allow symlinked directories as modules

---

Modules/feed/feed_controller.php
Modules/feed/feed_model.php
Modules/feed/feed_schema.php
Modules/vis/vis_object.php
Modules/vis/visualisations/editdaily.php
Modules/vis/visualisations/graph.js
Modules/vis/visualisations/graph.php
Modules/vis/visualisations/orderbars.php
Modules/vis/visualisations/simplezoom.php
Modules/vis/visualisations/stacked.php
Modules/vis/visualisations/stackedsolar.php
Modules/vis/visualisations/zoom.php
Modules/vis/widget/vis_render.js
default.emonpi.settings.php
default.settings.php
index.php
scripts/export_montly_cron.php
scripts/feedwriter.php
scripts/input_queue_processor.php
scripts/old.phpmqtt_input.php
scripts/phpmqtt_input.php

See change log https://openenergymonitor.org/emon/node/11009

Emoncms 9.4 | 2016.03.15

---

Modules/feed/Views/feedlist_view.php
default.emonpi.settings.php
default.settings.php

https://github.com/emoncms/graph
In `settings.php`
```
// Default feed viewer: "vis/auto?feedid=" or "graph/" - requires module https://github.com/emoncms/graph
$feedviewpath = "graph/";
```

Enable support for setting Graph module as default feedviewer vis

---

Modules/vis/vis_object.php
Modules/vis/widget/vis_render.js
index.php

http://github.com/emoncms/graph
See pull https://github.com/emoncms/emoncms/pull/491
EmonPi Emoncms update will pull in new Graph module: https://github.com/openenergymonitor/emonpi/blob/master/emoncmsupdate#L54

Use new graph module as default feed viewer vis

---

Modules/admin/admin_main_view.php
Modules/process/process_processlist.php
Modules/vis/visualisations/editdaily.php
Modules/vis/visualisations/editrealtime.php
Modules/vis/visualisations/timestoredaily.php
locale.php

- Fixed error "Cannot read property 'scrollHeight' of null" in Admin Panel
- Fixed gethostbyaddr(): Address is not a valid IPv4 or IPv6 address --> Warning massage
- Fixed localization codes
- ~~Added 'Reset to ONE' process as opposite of 'Reset to ZERO'~~
- Other minor fixes

Master contribution (5 Fixes)

---

docs/LinuxInstall.md

in apache2 version 2.4.7+ the root directory is now /var/www/html and NOT /var/www

Update linux install instructions

---

.gitignore
Vagrantfile

Added vagrant development box
- Accessible on localhost:8080 on the host machine
- Included xdebug for debugging
- Based on Ubuntu 14.04 with php 5.6
Could integrate Redis etc but as a starting point this worked for me to get going. Opinions?

Added vagrant development box

---

Modules/vis/visualisations/stacked.php
Modules/vis/visualisations/stackedsolar.php

I didn't check if the bug still exist in other visualisations.

Bug in vis/Stacked[solar].php with day vs. daily

---

Modules/feed/feed_controller.php
Modules/feed/feed_model.php
Modules/user/profile/profile.php
docs/LinuxInstall.md
docs/RaspberryPi/MQTT.md
docs/RaspberryPi/read-only.md
index.php
readme.md
scripts/logger/logrotate.conf

https://github.com/emoncms/emoncms/releases

Emoncms 9.7 | 2016.05.25

---

index.php
route.php

- Inject all dependencies into router instead of relying on global objects
- Clean up code a little bit for readability
Do you guys have an opinion on using something like composer for autoloading/dependency management? 
Also what is your stance on adding tests?

Inject dependencies into router and clean up a little

---

.gitignore
.htaccess
index.php
php-info.php

- check for essential PHP modules e.g. MySQL, get text 
- Add `php-info.php` files and restrict access to this file from localhost or local network only

Error checking

---

Modules/input/que_input_controller.php
Modules/input/readme.md

Issue: blank list of inputs with use que_input_controller.
Feature:
- added _input_view_ in _que_input_controller_;
- removed limits for nodeid;
- added _set_processlist_ for subaction "set";
- changed readme.

Issue with que_input_controller

---

Modules/feed/feed_controller.php
readme.md

app2.js:175 ERROR: feed.getmeta invalid response: false
https://community.openenergymonitor.org/t/my-solar-history-data-not-same-as-power-view/1087/7

Fix read API key

---

readme.md

line 62 - removed extra end bracket
* [Emoncms Community Forum](https://community.openenergymonitor.org/c/emoncms])
-to-
* [Emoncms Community Forum](https://community.openenergymonitor.org/c/emoncms)

Correction to readme

---

Modules/admin/admin_main_view.php

Clean up the Admin Page on Windows Hosts, tested on WAMPSERVER (as per EmonCMS instructions)

Clean up Admin Page for Windows Hosts - Answer to Bug report #560

---

Modules/admin/admin_main_view.php
Modules/feed/feed_controller.php
Modules/vis/vis_object.php
Modules/vis/visualisations/realtime.php
Modules/vis/widget/vis_render.js
Theme/basic/embed.php
docs/RaspberryPi/MQTT.md
index.php
readme.md

- ios full-screen capability
- Add colour option to vis type
- Fix Linux specific code when running on windows

9.7.3 | 2016.09.28

---

Modules/vis/Views/multigraph_edit.js
Modules/vis/Views/vis_main_view.php
Modules/vis/visualisations/common/vis.helper.js
Modules/vis/visualisations/multigraph.php
Modules/vis/visualisations/multigraph/multigraph.js
Modules/vis/visualisations/orderbars.php
Modules/vis/visualisations/simplezoom.php
Modules/vis/visualisations/stacked.php
Modules/vis/visualisations/stackedsolar.php
Theme/basic/theme.php
index.php

- Added multigraph manual window config.
- Fix height of vis widgets to use user defined bound size

EmonCMS 9.7.4 | 2016.10.01

---

Modules/feed/engine/MysqlTimeSeries.php
Modules/feed/feed_model.php
Modules/vis/Views/multigraph_edit.js
Modules/vis/Views/vis_main_view.php
Modules/vis/visualisations/common/vis.helper.js
Modules/vis/visualisations/multigraph.php
Modules/vis/visualisations/multigraph/multigraph.js
Modules/vis/visualisations/orderbars.php
Modules/vis/visualisations/simplezoom.php
Modules/vis/visualisations/stacked.php
Modules/vis/visualisations/stackedsolar.php
Theme/basic/theme.php
index.php

Fix json responses with "'" for time and value, fields.
Tested only with Virtual and Mysql engines,
If other engine is wrong, change only the engine file, dont touch
feed_model.php as null values must be supported as valid response.

	Fix feed time and value type

---

Modules/feed/engine/PHPFina.php
Modules/feed/engine/PHPFiwa.php
Modules/feed/engine/TemplateEngine.php
Modules/feed/engine/VirtualFeed.php

Try to fix json API responses with engines: mysql, PHPFina and PHPFiwa.
Removes "'" from nemric values (time and value).

 	Fix json datatypes

---

scripts/phpmqtt_input.php

This is a small patch to enable the base topic for MQTT to have sub-topics just in case that is considered useful. This is of no use in standard configuration, only where data is being received from external MQTT broker with more complex topics. 
This has NOT been tested with standard emonpi + emonhub setup, but is working for achieving above in custom setup. I could do testing in near future. 
Some additional warning/error messages have been added to log as well to help debug. 
Other extensions could be to allow multiple bast topics.

Patch to enable 'multiple' MQTT base topics

---

Modules/vis/Views/vis_main_view.php
Modules/vis/vis_controller.php
Modules/vis/vis_object.php
Modules/vis/visualisations/zoom.php
Modules/vis/widget/vis_render.js

Fix for https://github.com/emoncms/emoncms/issues/564#issuecomment-251536646

Cyrillic fix on zoom graph.

---

Modules/feed/engine/MysqlTimeSeries.php
Modules/feed/engine/PHPFina.php
Modules/feed/engine/PHPFiwa.php
Modules/feed/engine/PHPTimeSeries.php
Modules/feed/engine/TemplateEngine.php
Modules/feed/engine/VirtualFeed.php
Modules/feed/feed_model.php
index.php

Fix cast in engines
Related to https://github.com/emoncms/emoncms/issues/573 , https://github.com/emoncms/emoncms/issues/540 and https://github.com/emoncms/emoncms/commit/69ce58471f551de0ccc990e7578223b9f0578c69

Emon CMS 9.7.5 | 2016.10.15 

---

Modules/admin/admin_main_view.php

See here: https://community.openenergymonitor.org/t/admin-display-currently-installed-emoncms-modules/1954/13

Bugfix for emoncms modules

---

Modules/admin/admin_main_view.php
Modules/feed/engine/TemplateEngine.php
Modules/vis/widget/vis_render.js
index.php

- Fix autoscrolling of log files e.g. emonpi update log [forum discussion](https://community.openenergymonitor.org/t/wouldnt-it-be-nice-if-the-log-windows-on-the-admin-page-would-scroll-before-your-eyes/1986/10) @AndyTaylorTweet 
- Add button to download log files from admin interface [forum discussion](https://community.openenergymonitor.org/t/option-to-save-log-files-with-a-click-on-the-button-in-the-admin-page/1987/5) @joyrider3774 
- Show installed Emoncms modules on admin interface: [forum discussion](https://community.openenergymonitor.org/t/admin-display-currently-installed-emoncms-modules/1954/13) 
- Show emonSD pre-built SD card release version on admin interface [forum discussion](https://community.openenergymonitor.org/t/new-feature-emoncms-admin-page-display-emonsd-version/1975 …

Emoncms 9.7.7 | 2016.10.24

---

index.php
readme.md

https://community.openenergymonitor.org/t/admin-display-currently-installed-emoncms-modules/1954/21

Improve emoncms installed modules display

---

Modules/admin/admin_main_view.php
Modules/vis/Views/vis_main_view.php
Modules/vis/visualisations/bargraph.php
Modules/vis/visualisations/compare.php
Modules/vis/visualisations/dailyhistogram/dailyhistogram.php
Modules/vis/visualisations/editdaily.php
Modules/vis/visualisations/editrealtime.php
Modules/vis/visualisations/graph.php
Modules/vis/visualisations/histgraph.php
Modules/vis/visualisations/multigraph.php
Modules/vis/visualisations/orderbars.php
Modules/vis/visualisations/orderthreshold.php
Modules/vis/visualisations/rawdata.php
Modules/vis/visualisations/realtime.php
Modules/vis/visualisations/simplezoom.php
Modules/vis/visualisations/stacked.php
Modules/vis/visualisations/stackedsolar.php
Modules/vis/visualisations/threshold.php
Modules/vis/visualisations/timestoredaily.php
Modules/vis/widget/vis_render.js
index.php

-> Code refactoring on admin module
-> VIS widgets default zoom configuratios:
Added: Realtime
Refactored: timestoredaily, threshold,  Rawdata
Reverted: bargraph (already had Interval to specify default zoom)

Emoncms 9.7.8 | 2016.11.10

---

Modules/vis/visualisations/bargraph.php
Modules/vis/widget/vis_render.js

Fix for https://github.com/emoncms/emoncms/pull/597
Discussion: https://github.com/emoncms/emoncms/pull/596

Restored BarGraph Initial Zoom option

---

Modules/vis/visualisations/bargraph.php
Modules/vis/widget/vis_render.js

Revert "Restored BarGraph Initial Zoom option"

---

process_settings.php

Resolves https://github.com/emoncms/emoncms/pull/603#issuecomment-261518635 by prefixing all environment variables with EMONCMS_.

Prefix environment variables with EMONCMS_

---

Modules/feed/Views/feedlist_view.php
Modules/user/profile/profile.php
Modules/user/user.js
Theme/basic/theme.php
docs/LinuxInstall.md
docs/RaspberryPi/MQTT.md
index.php
scripts/mqtt_input.service
scripts/phpmqtt_input.php

- Fix special characters in email @spikeheap [#620](https://github.com/emoncms/emoncms/pull/620)
- Fix link to 'Feed API' after first login re-direct
- Add systemd unit file and install docs for `phpmqtt_input` script, recommend use instead of initd for improved logging and script autro restarting in the event of a crash

Emoncms 9.7.9 | 2017.01.05

---

docs/RaspberryPi/MQTT.md

Read-me details of how to log MQTT info into emoncms log/console

Add option to add MQTT info to emoncms log

---

docs/RaspberryPi/MQTT.md
docs/RaspberryPi/readme.md

Update docs to ensure that the MYSQL database is created with utf8 encoding.

Create MYSQL db with utf8 decoding

---

Modules/input/input_controller.php

eg. supports `input/bulk.json?data=[[-10,16,1137],[-8,17,{"1": 1437},{"2":3164}],[-6,19,{"data": 1412},{"anotherData":3077}]]` 
Solves #337.

Adds support for named bulkInserts

---

Modules/input/Views/input_api.php

Closes #337 together with #615.

Adds descriptions for named keys using bulk insert

---

core.php

Make load_db_schema() aware of softlinks, to enable database table creation of
external modules

Added softlink support for module schemes

---

Modules/input/input_controller.php

Fixes #641 
This pull request replaces the previous one that added a `trim` around the keys to avoid a problem where parsing could introduce additional spaces in the input names.
The approach here is to add a new input field `fulljson` ('full' meaning 'parsed with full json parser') that is parsed differently (using `json_decode`) and leaving the other input fields as-is (parsed using the old string-splitting method).
The change also adds a check for the input having been valid before attempting to process it that was previously missing - this avoids a situation where PHP raises errors because the contents of `$data` were not of the expected type to iterate over.

Add mode for strict JSON input parsing.

---

Modules/admin/admin_main_view.php
docs/LinuxInstall.md
docs/gettext.md

Updating guides and missing echoes

---

Modules/admin/admin_controller.php
Modules/admin/admin_main_view.php

Requires sudoers entry (added as part of emonPi update): https://github.com/openenergymonitor/emonpi/blob/master/emoncms-filesystem

Add buttons in admin page to set control RO / RW file system (only on emonPi)

---

Modules/vis/visualisations/bargraph.php
Modules/vis/widget/vis_render.js

Incorrect commit reversion fixed (https://github.com/emoncms/emoncms/pull/604)
Bargraph changes:
+ Missing  initzoom option --> restored
+ Missing mode option --> restored

Fixed BarGraph Initial Zoom option 

---

Modules/feed/engine/PHPFina.php
Modules/feed/feed_controller.php
Modules/feed/feed_model.php
Modules/input/input_model.php
Modules/user/user_controller.php
Modules/user/user_model.php
Modules/vis/visualisations/bargraph.php
Modules/vis/widget/vis_render.js
default.emonpi.settings.php
default.settings.php
index.php
process_settings.php

https://github.com/emoncms/emoncms/releases/tag/9.8.6

Emoncms 9.8.6 | 2017.05.10

---

Modules/input/input_model.php
Modules/user/login_block.php
index.php

https://github.com/emoncms/emoncms/releases/tag/9.8.7

Emoncms 9.8.7 | 2017.06.16

---

Modules/admin/admin_main_view.php

Fix emonpiRelease developing errors for non-emonpi

---

Modules/admin/admin_main_view.php

Update the Module version code to include the module name form module.json if the field exists. Ref Pull Request #695 
Also replace a pair of "&" with the correct "&amp;"

Update admin_main_view.php #695

---

Theme/basic/emon-sun.css

Hi guys,
I noticed that the colors of the dropdown menu were still blue for the sun theme of pull request #688 and I felt the urgent need to fix that ;)
The checks will most probably fail again, as **!important** is still considered bad^^

Adjust sun-theme dropdown menu colors

---

docs/RaspberryPi/stretch.md

Added for discussion in the forum

Raspbian Stretch guide

---

docs/RaspberryPi/MQTT.md

Update MQTT docs for PHP7.0

---

docs/RaspberryPi/stretch.md

Add functionality and make guide easier to use

Update following forum feedback

---

docs/RaspberryPi/stretch.md

Combines enhancements & changes discussed in the forum.   
A further change regarding Mariadb security follows...

Update stretch build guide

---

Theme/basic/theme.php

Partially fixed the dashboard menu overflow

fix dashboard menu overflow

---

index.php

see the [Emoncms Graph module developments ](https://community.openenergymonitor.org/t/emoncms-graph-module-developments/1380/64?u=pb66) thread

Add friendly username/graph url route to graphs module

---

Modules/feed/feed_model.php
Modules/input/input_model.php
Modules/user/login_block.php
Modules/user/rememberme_model.php
Modules/user/user.js
Modules/user/user_model.php
index.php
scripts/phpmqtt_input.php

- fix bug: in set input and feed processlist function's to allow non-numeric function name and argument
- fix bug: missing userid in input load to redis functions
- fix bug: user/auth apikey read
- fix bug: in rememberme module which resulted in a failure to find rememberme session, sha1 function moved from mysql to php.
- improved error reporting for user login and register process
- improved error logging for mqtt_input script

Emoncms v9.8.24

---

Modules/input/input_methods.php
Modules/input/input_model.php
Modules/process/process_processlist.php
index.php

- Attempted fix for mqtt_input crash resulting from bind_param on 
- Avoid "Divide by zero" errors
- Fix case where csv value is null
- Allow forward slash in input process list text argument

v9.8.25: bug fixes

---

Modules/vis/Views/multigraph_edit.js
Modules/vis/Views/vis_main_view.php
Modules/vis/visualisations/multigraph.php
Modules/vis/visualisations/multigraph/multigraph.js

A few changes to multigraph to give the user more access to flot options
This is my first attempt with Github hence am I'm hoping that I've now got this correct and the diff suggests so

Multigraph enhancements

---

Modules/vis/visualisations/multigraph/multigraph.js

Lines 269-274 are the real change, the rest is swapping single for double quotes.

Fixed tooltip lookup for stacked charts and a few Codacy tweaks

---

docs/LinuxInstall.md
docs/RaspberryPi/MQTT.md
docs/RaspberryPi/readme.md

See https://community.openenergymonitor.org/t/updating-system-libraries-used-by-emoncms/6274/38
I've rolled back to the pre-merge version & re-added the changes which I believe @glynhudson was trying to implement.
@pb66 Paul, as these were mainly your updates, I'd be grateful if you could take a look please before merging.
Paul

Correct previous merge errors

---

Modules/admin/admin_main_view.php

Add 2 buttons in order to copy information related to server and client configuration

copy to clipboard server and client information - step 2

---

Modules/admin/admin_main_view.php

Adds 'copy system info' to clipboard for use in forum.

Merge Feature Branch into Master

---

scripts/phpmqtt_input.php

Make the search for a time key case insensitive and add in additional logging.
If time key has a string value, if that string is not valid use system time.

make time key case insensitive and add logging

---

Modules/feed/engine/CassandraEngine.php
default.emonpi.settings.php
default.settings.php
docs/Cassandra.md
process_settings.php

some of the changes were already done by @glynhudson but should not cause any trouble

address issue #706

---

default.settings.php
docs/RaspberryPi/readme.md
process_settings.php

Change the paths of the emoncms settings & data files.

Restructure data and settings paths

---

docs/RaspberryPi/readme.md
process_settings.php
readme.md

Mainly to consolidate changes made to install guides

Update restructure branch from master

---

Modules/input/Views/input_api.php
Modules/input/input_controller.php
docs/input_encrypted.md
index.php
param.php

v2 implementation of transport layer aes128cbc encryption, see original:
https://github.com/emoncms/emoncms/pull/710
- other input module changes separated and merged prior to this

transport layer aes128cbc encryption implementation

---

Modules/admin/admin_main_view.php

Before this PR, 
there is an issue with progress bar when language is set to French in the user profile (and probably for other languages): 
the bar is not visible due to a wrong formatting of the width value below : 
this PR fix this issue

fix visibility of progress bar with French language

---

Modules/vis/Views/vis_main_view.php

Correct the var 'multigraph_id'

---

docs/RaspberryPi/Low-write-mode.md

Stretch requires PHP7, so added location of `php.ini`  and line to replace

Updates PHP sessions instructions for php7

---

Modules/admin/admin_controller.php
Modules/feed/engine/PHPTimeSeries.php
Modules/vis/vis_controller.php
Modules/vis/visualisations/bargraph.php
Modules/vis/visualisations/editdaily.php
Modules/vis/visualisations/rawdata.php
core.php
default.emonpi.settings.php
default.settings.php
index.php

- improved security of $updatelogin database update option.
- phptimeseries getmeta returns npoints and the start time
- modifications to vis to support tag:name option in dashboards
- option to return without passing content variable in controllers

merge of master into stable v9.8.30

---

Modules/admin/admin_main_view.php

Fix regexp for retrive mosquitto 1.5 version number

Fix regexp for retrive mosquitto 1.5 version number

---

Lib/listjs/list.js

php already removes any possible scripting used in text fields. this fixes the display of the new value to the user.
https://github.com/emoncms/emoncms/issues/763

sanitized user text input that would be displayed in the DOM

---

Modules/process/process_processlist.php

Addition of 2 new processess to limit the value of an input before logging it to a feed. User can define the maximum and/or minimum values allowed

Added max_value and min_value processes

---

Lib/tablejs/table.js
Modules/feed/Views/feedlist_view.php
Modules/feed/feed.js
Modules/feed/feed_model.php

also added 1s to interval dropdown

added custom feed unit values

---

Lib/tablejs/table.js

please ignore previously incorrect pull request:
https://github.com/emoncms/emoncms/pull/868
must have merged incorrect branches.

checked for undefined. uses blank string

---

Lib/enum.php
Modules/feed/feed_model.php

thanks @davidski for spotting this issue: https://github.com/emoncms/emoncms/issues/685

added check for valid engine id

---

Theme/basic/emon-blue.css

it should now allow for 3 more items before cropping off. Fixes #876

increased the dropdown max-height fixes #876

---

Lib/tablejs/table.js
Modules/feed/feed_model.php

using filter_var() function before prepared statement

---

Modules/feed/feed_model.php
Modules/input/input_model.php

related to issue #765 
**do not pull** until everything that uses this regex is tested

allowed "{" and "}" in feed/input text values

---

Modules/user/user_model.php
Modules/user/user_schema.php

add null=true and print mysql error

---

Modules/admin/admin_main_view.php

Enable the file system ro / rw buttons according to its status

File system ro / rw buttons

---

Modules/process/process_processlist.php

Reverted the client ID due to discussions on this issue:
- Previous Pull Request: https://github.com/emoncms/emoncms/pull/907
Comments:
- Community Forum: https://community.openenergymonitor.org/t/a-question-over-whether-emoncms-is-compatible-with-mqtt/7180?u=pb66
- Pull Request: https://github.com/emoncms/emoncms/pull/823
I'll change it when an issue is created. 
thanks for the help @pb66 - I jumped the gun on this one!

removed clientid from mqtt connect()

---

Modules/user/user_model.php
default.emonpi.settings.php
default.settings.php
process_settings.php

I wanted the subject of the reset password email to be "MyHomeEnergyPlanner password reset" instead "emoncms password reset"

appname  moved from user_model.php to default.settings.php

---

Modules/user/user_model.php

fixes issue #489 
I've tested this locally but not on a 🍓pi
thanks to @gablau for the code

added path restriction to session_start()

---

Lib/misc/clipboard.js

added function to allow for custom messages to user when content is copied to clipboard
fixes https://github.com/emoncms/graph/issues/21
a pull request for that repo is also required to complete this fix

custom clipboard.js user messages

---

Modules/vis/visualisations/bargraph.php

corrected issue caused by js and css positioning the tooltip incorrectly
related to issue #673

corrected issue with css  layout of bargraph tooltip

---

Modules/input/input_model.php
scripts/input_queue_processor.php

Minor spelling typo

---

scripts/phpmqtt_input.php

See original https://github.com/emoncms/emoncms/pull/822

changes from https://github.com/emoncms/emoncms/pull/822

---

Modules/user/deleteuser.php

Sorry @Trystan, I have just realized that we are using the device support branch in ours emonCMS installation so I need this merged on this branch not in the master as you have already done (https://github.com/emoncms/emoncms/pull/938)

require_once feed and input models in delete_user

---

Lib/bootstrap-datetimepicker-0.0.11/js/bootstrap-datepicker.js
Modules/feed/Views/feedlist_view.php

related to issue #655 
added -1year and -2year buttons to simplify the feed trim() feature

added relative date buttons to feed trim form

---

Lib/email.php

Added the option to send Cc and Bcc emails

added cc and bcc to emails

---

Modules/user/user_model.php

fixed user->get_name() was returning username instead of name

---

Modules/eventp/eventp_processlist.php
Modules/feed/Views/feedlist_view_v2.php

supports multiple selections
checks for associated input process
fixes issue #950

added trim() and clear() to new layout

---

Modules/input/Views/device_view.php

added bootstrap columns to input device view

---

Modules/feed/Views/feedlist_view_v2.php

added feed unit to Edit modal overlay

---

Modules/feed/Views/feedlist_view_v2.php

only loads supported languages

scripted momentjs locale file load

---

Modules/feed/Views/feedlist_view_v2.php
Modules/input/Views/device_view.php

the first time the bootstrap collapse is called could cause issues. checking that the plugin is available before running

checking for bootstrap collapse plugin before running

---

Modules/feed/Views/feedlist_view_v2.php

fixes issue #989 
i just ran the call to set.json for each selected feed. not sure if I should have created a multi edit endpoint for the api?

allowed multiple feeds to be edited at the same time

---

Lib/responsive-linked-tables.js
Modules/feed/Views/feedlist_view_v2.php
Modules/input/Views/device_view.php

saved the device and feed list accordion states into a cookie
cookie checked on page load to pre-set the state

fixes issue #990

---

process_settings.php

> # not fully tested !
> ## not ready for pulling into master!! 
> related to issue #1054 (Copy & Paste monster bit **process_setting.php**)
@TrystanLea  I assume that these settings are not being used correctly or this issue would have been raised much sooner?...

fixed the mqtt settings being saved to incorrect array

---

Theme/basic/theme.php

fix horizontal scrolling issue on admin page
fixes #1055

removed the dependance on hammer js on views that need it

---

Modules/feed/Views/feedlist_view_v2.php

refers to device repo issue:
https://github.com/emoncms/device/issues/28

removed width restriction from unit dropdown

---

Theme/basic/theme.php

fix issue #1078 
@glynhudson - could you please test this on your mobile ... the version I see on my mobile doesn't have the need for horizontal scrolling as the list is resized to fit my screen.

removed the hammer.js interactions on non beta version views

---

Modules/feed/Views/feedlist_view_v2.php

checked for empty selection to remove error

---

Modules/feed/Views/feedlist_view_v2.php
Modules/feed/feed_model.php

fix issue #1066 
- feed->exists_tag_name() is now case sensitive
- clicking save now only effects the selected entries

fix issue with renaming feeds not being case sensitive

---

Modules/feed/Views/feedlist_view_v2.php

fix #1088 
[screenshot of changed tooltip]

remove the bs tooltip dependancy

---

Modules/input/Views/device_view.php

changed heading icons to black
fix #1085

changed heading wrench icon to cog in input list

---

Modules/input/Views/device_view.php

fix #1101 
[screenshot of cog icon tooltip]
[screenshot of wrench icon tooltip]

added tooltips to wrench and cog icon in input list

---

Theme/basic/theme.php

fix #1113 
[screenshot of new alert contents]

added more detail to the window.onerror event

---

scripts/services/feedwriter/feedwriter.service

https://community.openenergymonitor.org/t/development-feedwriter-systemd-service/9181/14

Update Feedwriter.service to restart on-failure

---

index.php

added the header `'Access-Control-Allow-Origin: *'` to allow the find script to load the /describe endpoint with ajax

added cors headers

---

Modules/feed/engine/PHPFina.php
Modules/feed/feed_controller.php
Modules/vis/visualisations/editrealtime.php

This PR makes it functional to edit a datarange of a PHPFINA feed via the editrealtime visualisation :
- You can multiply the values in the window by a float or a fraction
- You can replace the values in the window by NAN if they are erronous due to some communication problems
- You can convert all the values in the window to absolute values
cf the following issue :
https://github.com/emoncms/emoncms/issues/1141
and this PR :
https://github.com/emoncms/emoncms/pull/1142 
working only for the PHPFINA engine
is it what you were looking for when designing the editrealtime visualisation ? or yu want the process to inject first the data in Redis, the feewriter service being responsible for transferring everything into the feeds ?
Alex

datafeed edition for PHPFina engine

---

Modules/admin/admin_main_view.php

show status of running services on admin page

---

Modules/feed/Views/feedlist_view_v2.php
Theme/basic/theme.php

fix #1111 - added ability to pick nodes from list when editing feeds
also allowed js errors to be displayed in the console
[screenshot of new edit feed layout]

added autocomplete to node name field

---

Modules/admin/admin_main_view.php

showing green if  installed and running
showing red if installed and not running
fix #1150 
thanks @borpin for the `systemctl` command example in issue #1150

hidden uninstalled services

---

Lib/misc/autocomplete.css
Lib/misc/autocomplete.js
Modules/feed/Views/feedlist_view_v2.php
Modules/input/Views/device_view.php
Modules/process/Views/process_ui.js
Modules/process/Views/process_ui.php

added autocomplete to processlist "new feed"
fix #1112 
can now add feed name and node/tag name separatly 
re-used the autocomplete feature of feed tag edit screen:

moved autocomplete input to own js and css

---

Modules/vis/Views/vis_main_view.php
Modules/vis/visualisations/bargraph.php

fix #1123 
fullscreen graph now fills screen height

fixed height issue

---

Modules/feed/Views/feedlist_view_v2.php

fix #1056 
done the feed list but not the input list.
the `input list` _lastest update time_ comes from the Redis or MySQL. I'm not able to determine if a virtual feed updated the feed or not.
[screenshot of

not testing against virtual feeds (feed.engine==7)

---

scripts/phpmqtt_input.php

used the same connection error as emoncms

---

Modules/admin/admin_main_view.php

Make the 2 buttons explicit in what is being copied to the clipboard.

Make explicit what the button is copying

---

Lib/responsive-linked-tables.js
Modules/feed/Views/feedlist_view_v2.php

fix #988 
[screenshot of feed update statuses]
```
< 3 intervals = green
< 9 intervals = yellow
> 8 intervals = red
```

showing feed interval status with colour bars

---

Modules/admin/admin_main_view.php

Fix formatting errors as per issue #1197

Update copy server info to clipboard

---

index.php

Add IP Address to 'Invalid API key' error message to aid debugging
https://community.openenergymonitor.org/t/sync-continuously-hitting-emoncms-org/10134

Add IP Address to 'Invalid API key' error message

---

Modules/process/process_processlist.php

Process to take the absolute value of an input before logging to a feed.

Add absolute value process

---

Modules/admin/admin_controller.php
Modules/feed/feed_model.php
Modules/input/input_controller.php
Modules/input/input_methods.php
Modules/input/input_model.php
Modules/input/que_input_controller.php
Modules/schedule/schedule_model.php
Modules/user/user_model.php
Modules/vis/multigraph_model.php

Fix issue on regular expression containing an hyphen. Please see #1180

Fix php7.3 regexp

---

Modules/user/user_controller.php

Hi,
As part of the module we have made to use [Auth0](https://github.com/carboncoop/emonCMS_auth0) for single login between all the tools we use in CarbonCoop, we need to be able to logout from Auth0 when the user logs out from emonCMS.
This pull request adds calls to a "logout_hook"

Added hook on_logout

---

core.php

@glynhudson - this will stop the error you're seeing

added default function parameter to the view() function

---

Theme/basic/theme.php

should fix css and js caching issues that cause this layout

added version number to sidebar css and js

---

Lib/misc/sidebar.js
Modules/user/Views/bookmarks.php

added bookmarks:updated trigger to sidebar.js
renamed items on new event in bookmarks.php view
fix #1253 
user instructions now looks like this:

removed user instructions regarding dashboard bookmarks

---

Theme/basic/embed.php

https://github.com/emoncms/dashboard/issues/209
issue raised in dashboard repo relates to the emoncms theme.
corrected it here

added missing global js variable to embed theme

---

Modules/admin/admin_controller.php
Modules/feed/feed_controller.php
Modules/user/login_block.php
Modules/user/user.js
Modules/user/user_controller.php
Modules/user/user_menu.php
Modules/user/user_model.php
Theme/basic/theme.php
index.php

admin controller now redirects to login if required
modified login template to forward users back to referrer page
passing referrer to user/login
handling referrer in user_controller
added icon to login menu item
added referrer to user_model
added login icon to theme.php
fix #1262 
passing formatted message to user if controller / action combo not found
added icon to login page (removed large text)
time out logins now redirect to referring page

altered missing controller message

---

scripts/logger/logrotate

also sets ownership regardless

revise logrotate cron to create log directory if it doesn't exist.

---

Lib/misc/sidebar.js
Modules/user/Views/bookmarks.php
Modules/user/user_controller.php
Modules/user/user_model.php
Theme/basic/sidebar_view.php
Theme/basic/theme.php
core.php

submitted bookmarks as string
set_preferences now sanitizes and decodes ajax inputs
added more logger messages (info)
user/bookmarks stopped the default dashboard from mixing in
fix #1275

sanitized array inputs via POST

---

Lib/gridjs/grid.html
Lib/misc/sidebar.css
Theme/basic/emoncms-base.css
Theme/basic/theme.php

fix #1292 
footer now fixed at bottom of the content..

dashboard height fix

---

Modules/feed/Views/feedlist_view.php

fixed issue with user object being overwritten

---

Lib/user_locale.js
Modules/feed/Views/feedlist_view.php
Modules/input/Views/input_view.php

added tooltips for input devices
added translation placeholders for js values
modified user-locale.js to use global variable `_user`
fix #1300
latest input value is now the last to be hidden on smaller devices:
there is also now a tooltip showing all values... (don't think mobile users can see this??)

re-ordered responsive columns to keep latest value

---

Lib/misc/nav_functions.php

related to issue on dashboard repo issue https://github.com/emoncms/dashboard/issues/214
menu items can now apply an array as the `active` property so that the menu item can be highlighted on multiple paths

Dashboard 214 menu aliases

---

Modules/admin/admin_controller.php
Modules/admin/userlist_view.php
Modules/user/user_controller.php
core.php

fix #1298 
once header() sends user to new url run exit() to stop script
removed unrequired json endpoint setuser.json action
removed double encoding redirection url in login screen
pointed user list to html endpoint admin/setuser
corrected double encoded parameters in logout route

corrected user/setuser endpoint call

---

Modules/admin/admin_main_view.php

admin - stopped <buttons> from copying text to clipboard

---

Lib/gridjs/grid.html

allowed for success, error and always functions to be grid-data template has access to root status{}
this is related to an issue in the dashboard repo

enabled success/error notifications for text fields

---

Lib/misc/nav_functions.php

fix #1317 
the navigation now also works on systems without the `/emoncms/` path.

removed hardcoded path variable

---

Lib/misc/nav_functions.php

@TrystanLea this will pass the menu item's sort number to the function that make the `<a>` link for the menu item. I've commented out the rendering of the number on line 208
https://github.com/emoncms/emoncms/compare/master...emrysr:feature/pass-menu-order-to-makeLink?expand=1#diff-7a751e358df77c4f3cd52ed7087407ffR208

passed menu item order number to makeLink() function

---

Lib/misc/nav_functions.php

fix #1321 
thanks @borpin for spotting this... apparently `$_SERVER['REQUEST_SCHEME']` is not always available on all web servers (by default). I've changed it to check for the missing value.

checked for missing REQUEST_SCHEME

---

.travis.yml

It seems the individual tests are failing on 5.6 and Chrome (that's a different issue), but I've mostly got your travis tests working so they run...
And they all pass on 7.2, and FF passes on 5.6
See https://travis-ci.org/reedy/emoncms/builds/551952830

Unbreak travis tests

---

Modules/input/Views/input_view.js
Modules/input/Views/input_view.php
Modules/process/Views/process_ui.js

added select feature to inputs
fixed missing table variable in process_ui

added collapse feature to nodes

---

Modules/user/login_block.php

this will enable a user to login quickly with their keyboard as the login form will be in focus on page load.

username now autofocused

---

Modules/feed/Views/feedlist_view.php
Modules/input/Views/input_view.js
Modules/input/Views/input_view.php

modified "no input" and "no feed" position
added no margin to empty '#table' element
screenshots in issue discussion
fix #1326

kept the view title in view at all times

---

Modules/feed/Views/feedlist_view.php
Modules/input/Views/input_view.js
Modules/input/Views/input_view.php

Revert "kept the view title in view at all times"

---

Modules/feed/engine/Histogram.php

Include response to methods not implemented.

---

Modules/feed/Views/feedlist_view.php

added datatype to feedlist tooltips

---

Modules/feed/Views/feedlist_view.php

fix #1354 
[screenshot of feed list item showing a virtual feed's process list]

displayed processlist to the right of the feed size

---

Lib/misc/sidebar.css
Modules/user/user_menu.php
Theme/basic/menu_view.php
Theme/basic/sidebar_view.php
index.php

modified *_menu.php files to include text
used css to hide topnav menu text on narrow devices

added settings variable to show/hide menu text

---

Lib/units.php

added kW to units

---

Lib/misc/sidebar.js
Modules/vis/visualisations/bargraph.php
Modules/vis/visualisations/compare.php
Modules/vis/visualisations/histgraph.php
Modules/vis/visualisations/multigraph/multigraph.js
Modules/vis/visualisations/orderbars.php
Modules/vis/visualisations/orderthreshold.php
Modules/vis/visualisations/rawdata.php
Modules/vis/visualisations/realtime.php
Modules/vis/visualisations/simplezoom.php
Modules/vis/visualisations/stacked.php
Modules/vis/visualisations/stackedsolar.php
Modules/vis/visualisations/threshold.php
Modules/vis/visualisations/timecompare/timecompare.js
Modules/vis/visualisations/timestoredaily.php
Modules/vis/visualisations/zoom.php
Theme/basic/embed.php
Theme/basic/theme.php

added 'window.resized' custom event to embed.php
replaced window.resize event for window.resized (inc debounce) in vis
removed repeating triggers of shown.sidebar.collapse
related to https://github.com/emoncms/app/pull/106

moved 'window.resized' custom event to theme.php

---

Theme/basic/theme.php

Opens outgoing link in a new browser window with the rel="noopener" tag

Open github in a new window

---

Lib/gridjs/grid-demo.php
Lib/gridjs/grid.html

fix #1416 
this is not system critical.. just a demo of how the vue.js version of grid.js works
[screenshot of grid js layout of dashboard api data]

corrected reference to config module's version of vue.js

---

default-settings.ini
example.settings.ini

Minor modifications to default settings
Add some items to example settings file.

Update default settings and example setting

---

Modules/admin/admin_model.php

Add `demandshaper` service to the services array

Update admin_model.php with demandshaper service

---

Modules/process/process_processlist.php

New input processes: kwh_accumulator & log_to_feed_join

kwh accumulator join

---

Modules/admin/admin_model.php

outputted errors to log
fix #1494 
@tehnoinstyle / @borpin - I was unable to recreate the error that causes the Exception, however I have added the check based on the messages reported in the issue.
please let me know if this doesn't fix the errors you see.

added try/catch block arround file_exists() code

---

core.php
param.php

fix #1496 
removed depreciated get_magic_quotes
ran stripslashes() on array items

checked for array before running stripslashes()

---

Modules/vis/visualisations/realtime.php

fix #1520 
I have replaced a line in the javascript that was not checking for the correct values if empty.
this should fix the issue.

fixed js issue with vis/realtime not handling empty values

---

Modules/admin/admin_main_view.php
Modules/admin/static/admin_styles.css

I tried to make the list of modules more beautiful, if the module version is the same as the php version then it doesn't display it.

beautify list of php modules

---

Lib/dbschemasetup.php

Currently `dbschemasetup` supports only schemas with a single-field primary key. In some cases this may impose unnecessary limitations on design of a custom module. This pull request suggests an approach on handling compound keys with minimal changes to `dbschemasetup`.
A schema just indicates more than one column as a key and `db_schema_make_table` detects this case and generates the key as the `PRIMARY KEY` clause
For example, the following schema :
```
$schema['coolstuff'] = array(
'feedid' => array('type' => 'int(11)', 'Null'=>'NO', 'Key'=>'PRI'),
'time' => array('type' => 'int(11)', 'Null'=>'NO', 'Key'=>'PRI'),
'data' => array('type' => 'float', 'Null'=>'NO'),
);
```
is translated to the following SQL:
```
CREATE TABLE `coolstuff` (`feedid` int(11) NOT NULL, `time` int(11) NOT NULL, …
```

ADD: support for schemas with compound key

---

Modules/admin/admin_main_view.php

Removed 3 x occourances of " are causing invalid html. Firefox produes "="" chrome just ignores it.

Extra " causes invlid html

---

Modules/admin/userlist_view.php

Specific column added to hyperlink to the users profile page.

Update user table with extra column

---

Modules/input/Views/schedule.php

As per the title semicolon in the wrong place

semicolon in the wrong place

---

Modules/user/user_model.php

It's used in export_monthly_cron.php

Make Feed::csv_export_multi_prepare() public

---

.travis.yml

Test PHP 7.4 on travis

---

composer.json

Adds the requires to match those of the code content. redis not added as its not a required.

Add additional requirements

---

composer.json

jakub-onderka/php-parallel-lint is abandoned

Replace jakub-onderka/php-parallel-lint with php-parallel-lint/php-parallel-lint

---

docs/RaspberryPi/language_support.md

I am more used to using the command line that a gui so was scratching my head as to why I coulndn't install extra languages for testing. It's possible that this will be helpful to someone else.
I am not certain if the Pi needs rebooting after the languages are installed as I didn't check before doing a reboot. If its needed it can be added in.

How to add additional languages to the Pi

---

composer.json

Follows up a799bb8eaf21ac767e51f711c7f8888aee55b6e8

Make composer.json valid json again

---

Modules/admin/admin_controller.php

Check for no TTY Port on update

---

Lib/process_old_settings.php
scripts/phpmqtt_input.php
scripts/services/emoncms_mqtt/emoncms_mqtt.php

Hello,
this commit adds support for secure mqtt broker connections.
Thanks for merging.

Add support for secure mqtt connections

---

default-settings.ini

add example on how to use mqtt secure settings

---

Modules/feed/Views/feedlist_view.php
Modules/input/Views/input_view.js
Modules/input/Views/input_view.php

Recent changes to the input and feed lists seems to have broken something. This pull request reverts these changes for the time being until this can be reviewed more carefully.

revert recent input and feed list changes until further review

---

docs/CLI.md
scripts/emoncms-cli

Messed the script up totally 🙈 
- Fixed relative PHP imports (Miss the magic of composer auto-loading)
- Fix script output to print out updates, or no no migrations executed if nothing to run
- Tested against the emoncms-docker setup, removing tables and watching them get recreated.
PR with changes implemented: https://github.com/inverse/hassio-addon-emoncms/pull/27

[emoncms-cli] Fix script

---

Modules/admin/admin_main_view.php
Modules/admin/components_view.php
Modules/admin/userlist_view.php

Localization 05 2021

---

Modules/vis/Views/vis_main_view.php
Modules/vis/vis_object.php
Modules/vis/visualisations/psychrograph.js
Modules/vis/visualisations/psychrograph.php
Modules/vis/widget/vis_render.js

@TrystanLea : I would like these commits to merge to emoncms, if possible. Hope you will be interested :-)
This permits to create psychrometric diagrams to appreciate summer confort in a house.
commits are only located in the vis Module
To create a pshychrometric diagram, you need to build a multigraph with a temperature feed first and a relative humidity feed after. 
The multiphrap above is for one area one  but to compare multiple areas of your home, you may stack as many "TRH" pairs as you want in the multigraph and the resulting psychrometric diagram should be something like that : 
the blue trapeze is the confort area. So if you are here, no problem, everything is fine.
best
Alex

Psychrographs in the vis module

---

Modules/process/Views/process_ui.php
Modules/process/process_processlist.php

Fix process localization

---

Modules/feed/feed_menu.php
Modules/input/input_menu.php
Modules/schedule/schedule_menu.php
Modules/user/user_menu.php
core.php

Sidebar localization

---

Modules/admin/admin_main_view.php

fix poedit error message

---

Modules/input/Views/input_view.js
Modules/input/Views/input_view.php

Add localization 18 07 2021

---

Modules/feed/engine/PHPFina.php

this permits to write zeros correctly

to solve issue 1719

---

Lib/menu/menu.css
Lib/menu/menu.js
Theme/emoncms-base.css
Theme/theme.php
index.php

- Fix left menu system quirks
- Fix left scroll bar
- Add auto hide on first page load if menu is overlaying content
- Fix content centering / fitting on resize / screen rotation
- Add shadows to menus
- Improve readability contrast on menu mouse over
- Add auto hide top menu on scroll if no lateral menus are open
- Fix menu-l2-controls abnormal movement

Menu revamp

---

Modules/feed/engine/VirtualFeed.php
Modules/process/process_processlist.php

Virtual feeds: modification to use in-built feed engine averaging and daily, weekly, monthly timezone aligned requests
Implementation is also faster. E.g: loading one month of data at an hourly interval took ~215ms with the original implementation and is now about 12ms.
Results for a virtual feed (single source feed only) and the original feed are consistent (graph shows both plots overlayed):
With averaging on both and hourly interval:
Daily timezone aligned interval with averaging:

Virtual feeds: modification to use in-built feed engine averaging and daily, weekly, monthly timezone aligned requests

---

Modules/feed/Views/feedlist_view.php
Modules/feed/engine/CassandraEngine.php
Modules/feed/engine/MysqlTimeSeries.php
Modules/feed/engine/PHPFina.php
Modules/feed/engine/PHPFinaTest.php
Modules/feed/engine/PHPTimeSeries.php
Modules/feed/engine/RedisBuffer.php
Modules/feed/engine/TemplateEngine.php
Modules/feed/engine/VirtualFeed.php
Modules/feed/engine/shared_helper.php
Modules/feed/feed_controller.php
Modules/feed/feed_model.php

Improved csv export implementation to use new get_data_combined api enabling averaging and timezone aligned DMY exports.
Updated UI:

Csv export averaging dmy timezone support

---

Modules/feed/Views/feedlist_view.php

Extended dialog used to create virtual feeds to allow creation of other feed engines

New feed dialog

---

Modules/feed/Views/feedlist_view.php
Modules/feed/Views/importer.js
Modules/feed/Views/importer.php

New feature to make it easier to import CSV data into emoncms:
Import tool accessible from the bottom of the feed list interface: 
Paste in CSV data, automatic interval detection. Create new feed or import into existing feed:

tool to import csv data directly to an emoncms feed

---

Modules/feed/engine/PHPFina.php
Modules/feed/feed_controller.php
Modules/feed/feed_model.php

calculation of delta mode including current day, week, month, year on the server side

Feed model delta mode

---

Modules/feed/feed_model.php

I believe we should encourage the user to request less data points by reducing the time window.

Suggest the user asks for less data

---

Modules/vis/vis_controller.php

fix 8.1 issue with preg_replace function

---

Modules/feed/feed_model.php

Using Api when feed is deleted successfully null is returned in response.

add message when feed deleted successfully.

---

Modules/vis/visualisations/editrealtime.php

https://github.com/emoncms/emoncms/issues/1821

to solve issue 1821

---

docs/user_guide/import.md
docs/user_guide/update.md

Update the upgrade information add photo of emonPi SD Card location.
Make clearer this is the route to Upgrade the SD Card.

Update upgrade SD Card information

---

docs/user_guide/mqtt.md

re https://community.openenergymonitor.org/t/activating-mqtt-client-services/22819/

Update MQTT testing instructions

---

readme.md

Update install via emonScripts link

---

Modules/input/input_methods.php

Fix deprecated creation of dynamic property

---

.gitignore
Modules/vis/visualisations/simplezoom.php

* Based on calculations done in bargraph.php
* Fixes ability to draw graphs with delta = On.
Tested locally.  Without fix, kwhd graph is blank when delta = On.  With fix, graph is shown correctly.

Use floor/ceil for datastart/end on SimpleZoom khwd graph

---

composer.json

Follows up https://github.com/emoncms/emoncms/pull/1862 and 93fc7092276d36151a0ddb4a88432ab37a7a974b

composer.json: Fix version for ext-zlib

---

Modules/admin/Views/update_view.php
Modules/admin/admin_controller.php

Option to upload custom firmware, required EmonScripts update as well:

Custom firmware upload

---

.github/workflows/PHP.yml

Update github actions checkout to v4

Update github actions checkout to v4

---

Modules/admin/admin_model.php

Fixes issue caused in cc8d5260f3df106e1e6cc7d50ab14fd1f8e907b2
Reported in https://community.openenergymonitor.org/t/cant-update-emoncms-via-gui/26898

admin_model.php: Make runService public again

---

Modules/input/input_methods.php

Update to support add ip to device module on https://github.com/emoncms/device/pull/86

Add support to update device IP automaticaly
