Modules/feed/feed_model.php

I found a few days ago that my kWh counter was fixed at some round value (120.0) and wasn't growing anymore, despite consuming electricity. After some debugging, I found the problem was that the update query sent to MySQL was using the system decimal separator (a comma in my case), while MySQL doesn't take locale into account and always expects a dot. The result is that MySQL was ignoring all decimal places, effectively truncating the value.
The patch here pre-formats the float value to a format suitable for MySQL (10 fixed decimal positions, dot as a decimal separator), so it works well regardless of system locale.

Fixed bug when OS and MySQL are not using the same decimal separator

---

docs/LinuxInstall.md

existing link to emoncms.org page does not work.  I have updated it to point to the github MD file with the referenced instructions.

update link to gettext installation help

---

Modules/feed/feed_model.php

There was a typo in feed_model.php that made impossible to export feed data to CSV.

Fixed extra "$" that made impossible to export CSV

---

default.emonpi.settings.php

To ensure compatibility with Low-Write mode. If not disabled, and is then user selected, emoncms will crash.

Disable PHPFIWA feed engine

---

Modules/process/Views/process_ui.js
Modules/process/process_processlist.php

This commit:
- Adds some documentation for some undocumented processors.
- Fixes some spelling errors
- Changes the name of `kwhinc_to_kwhd` to `whinc_to_kwhd` to reflect that it operates on Watt-hour increments and not kWh increments.

ProcessList: add documentation and fix spelling

---

docs/RaspberryPi/install_Wheezy.md

Just adds a nore to advise user to point emonhub at the newly installed localhost emoncms rather than the default emoncms.org whilst adding the apikey

Update to install docs

---

Modules/vis/vis_object.php
Modules/vis/visualisations/timecompare.php
Modules/vis/visualisations/timecompare/timecompare.js
Modules/vis/widget/vis_render.js

I've created and been using a new visualization to allow you to more easily compare power / energy reading over time.
You select a feed and it will display multiple lines for that same feed at different times. For instance one line will be the current week, another line will be for the previous week, and a third line will be for two weeks ago. They are displayed on top of each other (like a multigraph) so you can quickly compare the data.
You can switch between comparing days, weeks, months, or years.
You can also specify how for back to go (how many lines to display).
You can also hide and restore any line in the graph by clicking the name of the line in the legend. So if one line is obscuring another, simply hide it.

New visualization that lets you overlay data from older time periods

---

Modules/vis/visualisations/multigraph/multigraph.js
Modules/vis/visualisations/timecompare/timecompare.js

I often have a multigraph where most of the lines are small values, but one line has large values that dominate the graph. When that happens, I cannot get a very good idea of what the other lines look like. Here's an example:
So I added the ability to toggle lines by clicking on the name of the line in the legend. When you toggle the line, I have the y axis rescale so you can see the lines with smaller values.
Here I have hidden furnace:
When a line is hidden, you can zoom or pan the graph without restoring the line. You can also change from daily to weekly, monthly etc views without restoring the lines. You can hide as many lines as you like and restore them whenever you want by clicking on the name in the legend again.

Created ability to toggle lines in multigraph

---

Modules/vis/Views/multigraph_edit.js
Modules/vis/visualisations/multigraph/multigraph.js

By default the multigraph legend includes a tag for the feeds. In my case it is "Node 1". This takes up space on the graph. The buttons to switch between week month, year etc also takes up space. This makes it hard to hover over a line to see the exact reading there.
I added an option to the multigraph editor that lets you turn off the tag. It is enabled by default.
With it unchecked, the tag is not displayed and the legend is smaller.

Added ability to hide tag name from multigraph legend

---

Modules/user/profile/clipboard.js
Modules/user/profile/profile.php
Modules/user/profile/qrcode.js

Add QR code generation to user profile information using the Google API.
This is a pre-cursor to an upgrade of the Android app to be able to scan in the QR code (rather than typing the huge API key).

Add QR code generation

---

Modules/admin/admin_main_view.php
index.php

Cleaned up the code around the graphs for RAM / disk usage.
Show RAM graph for Pi hardware only.
Show /var/log specifically when its mounted on tempfs
The reboot button does require a supporting change in `/etc/sudoers`
`,/sbin/shutdown` should be appended to the www-data line to allow Apache to be able to execute the shutdown command.
The reboot code has been setup such that it can ONLY be executed on Pi hardware, this is a safety measure to help reduce any risks on production class (read non raspberry pi) hardware.

Graph clean up, add reboot button.

---

Modules/vis/Views/multigraph_edit.js
Modules/vis/Views/vis_main_view.php
Modules/vis/visualisations/multigraph.php
Modules/vis/visualisations/multigraph/multigraph.js

Add new options on Multigraph:
Lines/Bars can be defined as 'stacked'. E.g. can be used to show usage on individual branch circuits combining to a total usage.
The graph can be set to 'auto refresh' periodically. So that a dashboard can be configured to automatically update with current data. (The automatic update will be disabled if the graph has been scrolled so that the current time is no longer the end of the graph)
Show/Hide Legend. Either for simple graphs where the title is all that's needed. Or on a dashboard where multiple graphs have the same legend & only needs shown once.

Multigraph, new options - stack, refresh

---

Modules/process/process_processlist.php

This error occurs when creating a virtual feed comprised of newly created feeds resulting in the list of feeds not displaying.

is_nan throws an error if used on empty string

---

Modules/vis/vis_object.php
Modules/vis/visualisations/realtime.php
Modules/vis/widget/vis_render.js

This pull request adds a colour option to the realtime visualisation type.

Add a colour option to the realtime visualisation type

---

Theme/basic/embed.php

This ensures that if you have `embed=1`, to have a page with no chrome, that you can use this successfully with "Add to home screen" on iOS.
Without this, when you open the "app" that gets added to the home screen, it just opens Safari rather than showing the page in full screen without Safari's chrome.
I believe the intended behaviour is to show it full screen. That way you can use `embed=1` and "Add to home screen" to make a dashboard that shows literally just the dashboard.

Add iOS full-screen app capability to embed=1 pages

---

Theme/basic/emon.css
Theme/basic/menu_view.php

This aids usability when you have a long list of items. Moving your mouse all the way down can be tedious. Scrolling the list is easier.
In particular this is useful when you have a long list of dashboards which ends up going off the screen. Now it'll scroll so you can get to all of the items. This was picked up here:
https://community.openenergymonitor.org/t/dashboard-menu-does-not-scroll-not-all-dashboards-accessible-from-it

Make dropdowns a maximum height and allow them to scroll

---

Modules/input/Views/input_api.php

As i found out in the sources that the input api accepted http post parameters using the http post "data" variable i updated the input api documentation and added examples for http post using curl.
I also updated the json http get & http post example to include multiple values as it is not clear with only one data value that you can add multiple values at once. This is however clear if you provide a sample with multiple inputs as you can then deduct from multiple values that one values is possible also. However deducting from one value that multiple are possible is not so clear. Hence the change.
I only tested the curl examples in windows, they should work in linux also but i'm not certain of the double quote syntax in linux, perhaps one of you using linux can double check them ?
edit: …

Update input api with http post section

---

Lib/flot/plugin/saveAsImage/README.md
Lib/flot/plugin/saveAsImage/jquery.flot.saveAsImage.js
Lib/flot/plugin/saveAsImage/lib/base64.js
Lib/flot/plugin/saveAsImage/lib/canvas2image.js
Modules/vis/Views/vis_main_view.php
Modules/vis/visualisations/bargraph.php
Modules/vis/visualisations/compare.php
Modules/vis/visualisations/dailyhistogram/dailyhistogram.php
Modules/vis/visualisations/dailyhistogram/graphs.js
Modules/vis/visualisations/editdaily.php
Modules/vis/visualisations/editrealtime.php
Modules/vis/visualisations/graph.js
Modules/vis/visualisations/graph.php
Modules/vis/visualisations/histgraph.php
Modules/vis/visualisations/multigraph.php
Modules/vis/visualisations/multigraph/multigraph.js
Modules/vis/visualisations/orderbars.php
Modules/vis/visualisations/orderthreshold.php
Modules/vis/visualisations/rawdata.php
Modules/vis/visualisations/realtime.php
Modules/vis/visualisations/simplezoom.php
Modules/vis/visualisations/stacked.php
Modules/vis/visualisations/stackedsolar.php
Modules/vis/visualisations/threshold.php
Modules/vis/visualisations/timecompare.php
Modules/vis/visualisations/timecompare/timecompare.js
Modules/vis/visualisations/timestoredaily.php
Modules/vis/visualisations/zoom.php
Modules/vis/visualisations/zoom/graphs.js

Added saveAsImage functionality to:
- timestoredaily
- editrealtime
- editdaily
- orderbars
- histgraph
- timecompare
- graph
- rawdata
- zoom
- stackedsolar
- stacked
- simplezoom
- realtime
- threshold
- orderthreshold
- dailyhistogram
- compare
- bargraph
- multigraph
_Note: The functionality is available clicking with the secondary mouse button_
Flot Plugins
http://www.flotcharts.org/plugins/
Plugin saveAsImage origin:
https://github.com/Jeff-Tian/jquery.flot.saveAsImage.js

Added "saveAsImage" functionality to Visualisations

---

Modules/admin/admin_main_view.php

All this does is list all the subfolders under Modules that have a .git file in the folder.
Default modules are hardcoded to be bolded to split them from any others that have been installed.
This relates to this thread:
https://community.openenergymonitor.org/t/admin-display-currently-installed-emoncms-modules/1954

PoC Code to list Modules in emoncms

---

Modules/admin/admin_controller.php

Replaced the reliance on 'tail' in the admin module.
Source PHP from here: http://tekkie.flashbit.net/php/tail-functionality-in-php
This should provide a like for like drop in for tail so that Windows server users can still get the log file displayed in the admin module.

Remove reliance on linux / unix tail command.

---

Modules/admin/admin_main_view.php

Requested by Glyn here: https://community.openenergymonitor.org/t/admin-display-currently-installed-emoncms-modules/1954/11
This should only display on Raspberry Pi hardware, and ONLY when using the emonPi SD Card image.

Add emonPi Release

---

Modules/admin/admin_controller.php
Modules/admin/admin_main_view.php

As per request of @glynhudson  i added a quick option to download the log file. I intentionally did not put text as content type so you always get a download box (depending on the browser) to choose where to save the file and don't view the file inside the browser.
I tested it on my windows and it seems to work fine for me should be tested on linux

Option to save log files with a click on the button in the admin page

---

Modules/vis/visualisations/bargraph.php
Modules/vis/visualisations/rawdata.php
Modules/vis/visualisations/threshold.php
Modules/vis/visualisations/timestoredaily.php
Modules/vis/widget/vis_render.js

Default zoom level of the radata visualization (day , week, month, year) in the configuration panel.
By default the visualization uses week zoom. The zoom level selection is robust to unexpected values or undefined value.
It could be extended to other visualizations. I can prepare another PR to do that.

Initial zoom level option in Visualizations

---

Modules/admin/admin_main_view.php

Some Linux hosts do not allow access to '/proc/meminfo' in the case of some VPS services.
Actually check to make sure /proc/meminfo is available (remove error messages from those cases where its not available.)

Additional checking for memory information

---

process_settings.php

A belated follow-up to https://github.com/emoncms/emoncms/pull/547. 
This change adds the ability to define some core settings as environment variables. When set, environment variables take precedence over `settings.php` and defaults. This enables Docker (and other services) to provision emoncms without needing to alter the default settings file at all, and (for example) allows the same codebase to be run against different environments for testing.
This doesn't affect the behaviour on systems where the environment variables are not set.

Enable environment-variable settings in default.settings.php

---

process_settings.php

This PR improves the recently merged environment variable support (https://github.com/emoncms/emoncms/pull/602) by validating the setup _after_ the environment variables have been pulled in. This has a couple of benefits:
1. In a setup where environment variables are used, the config no longer needs to be duplicated in `settings.php`, but omitting the config from _both_ yields the correct error.
2. Any validation added in future will be applied to values loaded from environment variables, making the behaviour consistent across config approaches.

Validate variables after environment loaded

---

Modules/user/profile/profile.php
Modules/user/user.js

This PR resolves #616. 
The cause of #616 was illegal URI characters (in this case a `+`) being replaced with ` `, which in turn results in an illegal email address on the server.
Encoding all URI components is sensible because it also prevents spurious input from having unintended consequences (e.g. if a user entered the username `bob&email=somethingelse@gmail.com`). 
I've tested this change locally and it fixed it for the `+` character issue at least.

Encode URL GET params for registration, password change, etc.

---

Modules/feed/Views/feedlist_view.php

As raised by pb66, removing the readme section about init.d systems, stops non systemd users from running the mqtt_input script.

MQTT script support for non systemd systems

---

Modules/vis/multigraph_model.php

Hello,
the multigraph labels mangle unicode sequences dropping them from labels in multigraph, even when they are permitted in feed names. I have changed the line to match the pattern on $name line and permit unicode sequences as well.

Support for unicode characters in multigraph labels

---

Modules/process/process_model.php

Modules with only a softlink in the Modules directory do not get their *_processlist.php processed correctly. 
Make Process->load_modules() aware of softlinks, to enable custon processes of external modules.
Almost identical to my last pull request regarding [module schemas](https://github.com/emoncms/emoncms/pull/651) and again just a very (very) small commit :)

Add softlink support for module processlists

---

Modules/admin/admin_main_view.php

See issue #660 and issue #663.
The php modules are in alphabetical order, round brackets removed, added "v" for version.

Display phpmodules versions on admin page - Part 2

---

Modules/feed/engine/PHPFina.php

Hi, I've discovered a bug when requesting data from "get_data_DMY_time_of_day" on 30 minute split points, which causes duplicate data to be returned.   Looks like a simple Python floating point number rounding issue.
I've also increased maximum split points from 24 to 48 to allow a days worth of 30 minute data to be returned for a new energy cost comparison (time of use based) app for emoncms.

Fixed issue with split on 30 minute interval

---

Modules/admin/admin_main_view.php

...For consistency with emoncms modules list

Add separator between PHP module names

---

Modules/admin/module.json
Modules/eventp/module.json
Modules/feed/module.json
Modules/input/module.json
Modules/process/module.json
Modules/schedule/module.json
Modules/time/module.json
Modules/user/module.json
Modules/vis/module.json

As a number of the modules are included in the main emoncms repo (& unlikely to be moved) it has created a mismatch of capitalized and lower-case names in the module list.
By adding a module.json file to each of the core modules too (minus the versioning), we can create capitalized 'friendly' name for all modules.
Let me know if you want me to progress this.
Example;
Before -
After -

Add module.json to core modules?

---

Modules/user/user_model.php

This is similar to the `get_username($userid)` function except it returns the My Profile name rather than the user name.
This can be used in a bespoke Theme to add a friendly name (including spaces) to the nav bar for example.

Add ability to get account name from the userid

---

Lib/email.php

This comes up a lot on the forum. The PEAR PECL installer installs the swift_required.php file to the same location as the Swift folder not in the Swift folder, since the PEAR PECL installer is the recommended install method this is where emoncms is most likely to find it.
(for example forum mention see https://community.openenergymonitor.org/t/emoncms-org-email-reports/4519/6?u=pb66)

Correction to swift_required.php path

---

Modules/admin/admin_main_view.php

Removed the "MySQL" prefix to the currently installed version as the installed mysql DB maybe mariaDB not Oracle MySQL. Also changed the section name from database to MySQL as the core database is always mysql, regardless of whether it is Oracle or MariaDB.

Adjust admin view to also accommodate mariadb

---

Modules/input/input_model.php

Hi guys,
this is just a very small pullrequest to fix a bug in `load_input_to_redis($inputid)`, where 
`$this->redis->sAdd("user:inputs:$userid", $row->id);` called a `$userid` object that is undefined.
This only occurred if you by chance call something extraordinary like */emoncms/input/process/get?inputid=1* immediately after flushing redis ;)
Additionally, I added a public function to get the last timevalue to the input model as I thought it cannot hurt and I possibly could like to use it someday^^

Fix missing $userid in input redis function

---

Modules/input/input_model.php

Well, the german word is verschlimmbessern for what happened here^^
I accidentally slipped a `fetch_array` instead of an `fetch_object` in, with #742 - breaking everything as bad as the missing userid did :)
Sorry for that.

Fix load_input_to_redis

---

Modules/process/process_processlist.php

(See https://community.openenergymonitor.org/t/emonhub-crashed-with-oom-error-in-var-log-messages/5814?u=pb66)
Avoid an error when the $time_diff is zero due to the new $time value being equal to the $last_feed['time'] eg same data posted twice.

Avoid "Divide by zero" errors

---

Modules/admin/admin_main_view.php

Memory	RAM	Used 53.44%Total: 875.78 MB Used: 468.02 MB Free: 407.76 MB
Swap	Used 76.32%Total: 100 MB Used: 76.31 MB Free: 23.68 MB
Adds colon to 'Used' & space after '%'
Remove whitespace
@thib66 The clipboard copies 'Shutdown/Reboot' alongside the CPU Temp, could we use Regex to ensure it's not displayed?

Add formatting to improve clipboard render

---

Modules/feed/engine/PHPFina.php
Theme/basic/emon-standard.css

Changed the logic in PHPFina.php for get_data_DMY() to:
1. When storing the value in the array, remove the "$time<$end" as this was preventing the return of the last value and is also not required as the 'break' will prevent going past the end. This was also causing disparity with get_data() for the same date ranges
2. 'streamlined' the loop by making $increment a value which is defined once outside of the loop

 Change get_data_DMY() to return all requested values

---

Modules/user/user_schema.php

If 'tags' has no default value, the sql query for user registration will
silently fail.
Also see this thread regarding this issue:
https://community.openenergymonitor.org/t/emoncms-error-creating-user/6490/19
Thanks to @belba who found the culprit of the error.

user registration fails if no default for 'tags' is set

---

docs/RaspberryPi/readme.md

As discussed [here](https://community.openenergymonitor.org/t/install-dependencies/6530/7)

Install php-redis via pecl to get v3.1.3

---

Modules/process/Views/process_ui.js

Changed alignment of the first down arrow within the process reorder list within "emoncms/input/view" when editing the input process list so that it will align to the right hand column and thereby make it easier to follow.
Also the hover over text for the down arrow has been corrected from "up" to "down", example of both:

Input process list - tidy reordering arrows

---

Modules/admin/admin_main_view.php

Fixes https://community.openenergymonitor.org/t/error-after-update-to-v9-8-28/6629/2
I'm sure there is a more elegant way of writing this fix!
Also, it's untested on emonpi (as I don't have one!)
Paul

Fix test for emonpi

---

docs/LinuxInstall.md

ntp and ufw aren't related to the functionality of emoncms; i.e. they are not dependencies. NTP already was removed from the Raspberry Pi installation instructions with 6eddfdd1ee6111607a5bbb4d14502dc8c8951381
General cleanup of sudo-code blocks to make them more readable. Removed unnecessary linking of the site configuration as this is handled by `a2enmod`

remove ntp, ufw from package list; clean up sudo-code

---

Modules/input/input_model.php

See https://github.com/emoncms/emoncms/commit/5ca10931f577dad65beb188c2a5f9f2bb4c74ce8 and OEM forum thread https://community.openenergymonitor.org/t/input-list-doesnt-load/3797/65?u=pb66.
It seems the fix has inadvertently been removed with this commit https://github.com/emoncms/emoncms/commit/a425e250f408c53c1cc1c6b0fbe690f6bd6091f8

Re-implement fix for input page not loading

---

Modules/input/input_controller.php

I started getting some error messages in the logs, like below
```
2018-04-23 23:07:51.950|ERROR|input_controller.php|{"success": false, "message": "Format error, json string supplied is not valid"}
2018-04-24 09:07:56.114|ERROR|input_controller.php|{"success": false, "message": "Format error, json string supplied is not valid"}
```
But had no idea which of the many accounts I have logging data to this server the messages belonged to so I added a "userid" to the log message so that the log messages now read like so
```
2018-04-24 13:56:08.751|ERROR|input_controller.php|{"success": false, "message": "Format error, json string supplied is not valid"} for User: 12
```

Added user id to logged error messages

---

Modules/user/user_model.php

The get_name () method was trying to fetch the wrong column from the table. EMonCMS doesn't use this method anywhere but we use it in MyHomeEnergyPlanner, that's why I spotted it

fixed get_name() in user model

---

.gitignore
Modules/schedule/schedule_menu.php

Hi guys,
with me using eclipse PDT to look into emoncms for years now and having these changes locally, I finally thought to maybe just start a PR about this.
Maybe these small changes to the gitignore do not clutter up too much? 😄 would be strongly apreciated
Further, I took the audacity to increased the schedule menu order from 1 to 10, reflecting the corresponding input order and allowing other modules to be placed at top.

Add Eclipse PDT files to gitignore

---

Modules/admin/admin_main_view.php
Modules/admin/pi-model.json

Improved the "pi" section in the administration panel:
- added exact Model, through revision codes. (https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md)
- added SoC and serial number, through /proc/cpuinfo
- added GPU temperature, requires user "www-data" in the "video" group, otherwise it will not be shown (cmd "sudo usermod -G video www-data")
- added current filesystem status ro / rw, via "mount" command
Preview of changes made see the red dots:

Improved "Pi" section in the administration panel

---

docs/Upgrading.md

The upgrade instructions explain how to update the DB even when not being able to login. The URL was not correct, fixed by this commit.

correct db update URL in docs

---

Modules/user/deleteuser.php
Modules/user/user_controller.php
core.php

In [this forum post](https://community.openenergymonitor.org/t/emoncms-org-terms-of-use-and-privacy-policy/7437/2?u=cagabi) it came up the need of a way to tell not core modules to delete user's data when the user deletes his/her account. 
The original implementation of "delete user" looks for the userid in handcoded tables but that will not work for other modules not included so far. In my case I need to implement this functionality for the task module. So the solution is a hooking system (this pull request :). An implementation of a hook can be found in [the group module](https://github.com/emoncms/group/blob/master/group_hooks.php#L20)

Hooking system

---

Modules/process/process_processlist.php
scripts/phpmqtt_input.php

- removed mqtt->loopForever()
- moved mqtt->disconnect() out of the mqtt->onConnect() callback
- new Mosquitto\Client() now randomises the clientID and cleans out connections
not 100% sure these changes will fix the issue? not totally sure what the issue is.. **can't re-create it** !?
1. https://community.openenergymonitor.org/t/mqtt-log-entries/7784
1. https://community.openenergymonitor.org/t/mqtt-too-much-subscriptions-to-local-broker/2202
1. https://community.openenergymonitor.org/t/strange-emoncms-mqtt-publish-phenomena-not-solved-but-the-reasons-understood-see-https-community-openenergymonitor-org-t-mqtt-log-entries-7784/7793
1. https://community.openenergymonitor.org/t/another-emonpi-stopped-logging-thread/7267/21?u=borpin
could be..
- mqtt publish clientid conflict on multiple …

try to fix mqtt issue with concurrent connections

---

Modules/user/user_model.php

Three bugs fixed:
- When email could not be sent the  string to write into log file was malformed giving  an 'undefined' error in login block instead of 'An error occured'
- When email was not be sent , the message shown to the user was "Password recovery email sent!"
- New password was written into the database before checking $enable_password_reset is enabled and before sending the email. I have changed it to write the password into the database only if $enable_password_reset is true and if the email has been successfully sent

Fixed password reset bugs

---

Modules/vis/visualisations/bargraph.php

fixes #673 
TEXT WAS OVERLAYING BUTTONS
FIXED BUY MOVING TEXT

moved bargraph value hover container to centre bottom

---

Modules/input/Views/input_api.php
Modules/input/input_methods.php
scripts/phpmqtt_input.php

Fix for issue #777 and a replacement PR for #804.
Validate the time input value for both the API (less bulk input) and MQTT input, to allow time to be in ISO string and seconds.
Updated validation of time input to MQTT to make more robust. Used same method in input_mthods so both input methods allow same time format.
Updated API help page.
Not tested any impact to bulk upload method. Should be none.

Modify time validation for API and MQTT input

---

Modules/user/user_model.php

#918 introduced a fix for cookies so that if emoncms is running at e.g. domain.net/emoncms, then cookies it saves would be restricted to that path and below.  However it also broke logins if Emon is running not in a subdirectory because it set a restriction to the path `//` rather than `/`.  This pull request fixes that behaviour.

Fix cookie path restriction when running on domain root

---

Modules/user/deleteuser.php

After a while we are using in the Group module the delete_user function to fully remove users. We call this function from inside the group_model where the feed and input models have already been required

require_once feed and input models in delete_user

---

.htaccess

This is required to use Let's Encrypt SSL certificates.

Allow access to .well-known for certbot (#952)

---

.travis.yml

PHP 5.4 is older than the version listed under 'requirements' in the README and the PHPFina tests always fail on it, so I removed it and 5.5 from the Travis php version list and replaced them with 7.1 and 7.2.

Remove test-failing PHP versions from Travis CI

---

docs/RaspberryPi/Low-write-mode.md

See https://community.openenergymonitor.org/t/feeds-are-missing-after-reboot/8193/33?u=pb66
sudo su is required as sudo alone doesn't work

additional correction

---

Modules/admin/admin_main_view.php

Add the Git URL and the branch into the administration module.  When answering queries, it is often useful to know which branch the user is on as some questions may have already been solved in the master branch.
I have taken the URL from ls-remote. Not being an expert on Git this may not be the best method but was the only one I could find to just get the origin URL.

Add Git info to administration page

---

Modules/input/Views/input_api.php

fixes issue #956 - Wrong link
changed dead link from:
https://github.com/emoncms/emoncms/blob/input-improvements/docs/input_encrypted.md
to:
https://github.com/emoncms/emoncms/blob/57f75aee6948c96d31ad023ae49289b04d832f1e/docs/input_encrypted.md
not sure if this is the correct location but works for now

updated link

---

Modules/feed/engine/PHPFina.php

Hi,
Every now and again when checking the log file we found some warnings that seemed to have no reason and were worrying us:
`2018-09-11 12:44:29.099|WARN|PHPFina.php|get_meta() meta file does not exist '/var/lib/phpfina/130.meta'`
After having a look we noticed the warnings happened when we were creating the feeds. The warning was triggered by the the get_meta() method of the phpFINA engine that was used to check if the feed exists before creating it. I have changed it to just check the meta data file exists which is the first thing that get_meta() does

Removed warning in log file when creating phpfina feed

---

Modules/admin/admin_main_view.php

Issue #1012 identified an issue with the command to retrieve the current branch in that it did not always get the right branch.
The git branch command retrieved all branches not just the current one.
2 solutions were identified git branch --contains HEAD and git rev-parse --abbrev-ref HEAD.
I have chosen the former.

Update command to get correct git branch

---

Lib/dbschemasetup.php
Modules/user/user_schema.php

This pull request refactors `dbschemasetup.php` to remove code duplication and logic inconsistencies, fixes several bugs, and adds documentation.  I started doing this when trying to set up emoncms master, I bumped into the issue with the user table's `tags` column being set to NOT NULL, and I refactored to try and work out what was going on.  This is the result!
There are three cases when this file creates or updates a column in the database:
1. when adding a new table
2. when adding a new column to an existing table, and
3. when altering an existing column
All these cases currently use different logic, resulting in inconsistencies.  For a column that has 'null'=false, in cases 1 and 3 it is not given a NOT NULL constraint, but in case 2 it is.  If 'null'=true, however, in cases 1 and 2 …

fix for #791 & refactor and fix bugs in dbschemasetup

---

scripts/services/install-service-runner-update.md
scripts/services/service-runner/service-runner.py
scripts/services/service-runner/service-runner.service

Added a new python based service-runner and .service file to enable it to run as a service under systemd.
This should replace the service-runner bash script included in other repos that require service-runner.
Previously these changes  were in a PR to https://github.com/openenergymonitor/emonpi but part of that discussion suggested moving this function to emoncms. For the previous discussions, see https://github.com/openenergymonitor/emonpi/pull/67 and https://github.com/openenergymonitor/emonpi/pull/66
For this PR, I have created a new `services` directory under scripts with a `service-runner` directory underneath containing the actual .service and .py files.
I left the documentation file for it in the `scripts/services/` directory, but can move it down one level if people think that …

Added systemd based service-runner in python

---

.gitignore

if `/vendor/` is not added to `.gitignore` all the dependent packages (including ones for development) will be added to the repository
Added composer to help with managing packages that parse static config files (#1001) ( pull request #1024 ) .
This line is already in the pull request branch `emrysr:feature/issue-1001-common-units`, however as this directory is ignored it is not removed when I switch branches.

added composer packages directory to .gitignore

---

Modules/feed/Views/feedlist_view_v2.php

issue #1029 - Feed page hover-over info not clear as to which feed it belongs to
pr #1047 - issue 1029 feed tag in tooltip
fix for js error caused by pr #1047 - issue 1029 feed tag in tooltip

added the mousePos variable to the global scope to fix error

---

Theme/basic/theme.php

this will allow mobile users to still scroll / drag the page vertically
fix #1055

locked the swipe navigation to horizontal only.

---

Theme/basic/theme.php

fix #985 
swiping to navigate between inputs and feeds only works on mobile now.
this is to stop unwanted navigation when highlighting text with a mouse

restricted swipes to mobile devices

---

scripts/services/install-service-runner-update.md
scripts/services/service-runner/service-runner.py
scripts/services/service-runner/service-runner.service

As discussed: 
https://github.com/emoncms/emoncms/pull/1025 
https://github.com/openenergymonitor/emonpi/pull/65 
https://github.com/openenergymonitor/emonpi/pull/66 
https://github.com/openenergymonitor/emonpi/pull/67
* Added systemd based service-runner in python
Added a new python based service-runner and .service file to enable it to run as
a service under systemd.
This should replace the service-runner.sh bash script included in other repos
that require service-runner.
* Fixed path to script in the .service file
* Tidied up the documentation
* Try and appease the automated code review

Added systemd based service-runner in python (#1025)

---

Modules/input/Views/device_view.php

While I [was working on the device module](https://github.com/emoncms/device/pull/30) I noticed the `"Configure your device here"` message could direct the user better with an arrow pointing at the correct button:
the message disappears once a device has been initialized and is saving to a feed

 added arrow to "configure your devices" alert for first timers

---

route.php

while testing the `Authorization: Bearer APIKEY` as per the emoncms `/feed/api` in the browser I got issues with the [CORS preflight request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) not returning the expected headers
**used during development the remote calls to the api**
before this is pulled in, we'll need to discuss the pros and cons of the `allow-origin` header being set to `*` (all). 
``` 
'Access-Control-Allow-Origin: *'
```
might be better to be set to `openenergymonitor.org` if that is where the requests will be originating from?
These are the HTTP headers I'm returning when a HTTP `OPTIONS` request  is made to the API. 
_(my changes don't effect GET or POST requests)_
```
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: …
```

added CORS complient preflight headers

---

Modules/admin/admin_main_view.php

Fixes #1076 
The \<pre> tag appears to stop the table from rendering correctly when pasted into a git issue.

Remove <pre> tags to render in git correctly

---

docs/LinuxInstall.md

Ubuntu 18.04 uses PHP 7.2.
Depreciated php-mcrypt is gone now.

Update LinuxInstall.md for Ubuntu 18.04

---

Modules/feed/engine/PHPFina.php
scripts/feedwriter.php

This is to fix the issue highlighted in the forum thread here: https://community.openenergymonitor.org/t/getting-spikes-in-emoncms-graph/9494/26
@chaveiro for some reason the use of static $lastvalue_static_cache did not store the last value as expected. Changing to a private variable array seems to work much better. Can you see any issue with this approach?

fix padding spikes where input feed has null value

---

index.php

Bugfix for: "No error or output shown when json_encode() returns an error."
This error causes a lot of searching when debugging, for example when there is an invalid character in a string.

No error or output shown when json_encode() returns an error.

---

default.settings.php
index.php

Prefixes for keys are handy, but redis supports multiple separate dbs entirely,
via "select".  Expose that as a configuration setting.
Signed-off-by: Karl Palsson <karlp@tweak.net.au>
--
I didn't find any real place to add documentation for this, there's nothing for the auth option either?

redis: support db selection via dbnum config

---

Modules/input/Views/device_view.php

fix #1154 
[screenshot of hidden buttons when device list empty]

hidden controls when list is empty

---

scripts/phpmqtt_input.php

Quick fix to replace colons in MQTT topic names as EmonCMS cannot handle them in node names.
This should be reviewed and any other characters that are legal for MQTT topics, that EmonCMS cannot handle in node names, also replaced.
Ref #1106 that I accidentally closed
Issue #1105

Replace colons in MQTT Topics

---

Modules/process/Views/process_ui.js
Modules/process/Views/process_ui.php

corrected <option> value quotes
fix #1139
Currently selected feed cannot be used as the source feed when editing process list for a virtual feed.
> I've just hidden the `<option>` that had the same feed id as the currently selected feed.
thanks @erikfleischer for the help

hidden currently selected feed from feed list

---

Modules/admin/admin_main_view.php

fix #1129 
this line will now be hidden (`/emonmcms/admin/view`) on the newer images of emoncms that don't have the filesystem read only restriction:
```
if (file_exists('/usr/bin/rpi-rw')) {
```

checked for rpi-rw script to identify older version

---

scripts/mqtt_input.service
scripts/services/feedwriter/feedwriter.service
scripts/services/install-service-feedwriter.md
scripts/services/install-service-runner-update.md
scripts/services/service-runner/service-runner.service

Changes made for sake of consistency (mostly).
Service-runner
* remove user Pi (#1069 refers). Document and comments updated.
* Restart on failure (same as feedwriter)
* documentation link updated
* Update instructions to uninstall/disable old service-runner
feedwriter
* had a 'wants' entry of `redis.service` corrected to `redis-server.service`
* documentation updated.

Tidy feedwriter, service-runner and mqtt_input services

---

scripts/services/service-runner/service-runner.py

Resolve issue whereby the different default redis prefix used in emonpi default settings and default settings mean that service runner was unable to get the right item off the queue.
As discussed in #1167 
This is only a temporary fix as any prefix could actually be used.

Update to service-runner.py for redis prefix

---

Modules/admin/admin_main_view.php

**Needs Testing**
Discussion https://community.openenergymonitor.org/t/long-mount-points-disrupt-server-information/10089
Long mount points disrupt server information on admin page.  This PR limits the display to 30 characters plus ellipse.  There may be something clever to display the full path when it is moused over.

Limit size of Mount point text

---

Theme/basic/theme.php
index.php

fix #1199 
I'm able to remove the full url and only show the relative path within the information shown in the alert, however, the alert title and button is controlled by the browser.

Feature/issue 1199/remove url from js error messages

---

Modules/admin/admin_controller.php
Modules/admin/admin_main_view.php

Increased flexibility for the update process. 
Update Options: All, Emoncms, EmonHub, Firmware, Database

Update Options: All, Emoncms, EmonHub, Firmware, Database

---

Modules/feed/feed_model.php

There appears to be an error in evaluating the engine number such that creating virtual feeds fails. https://community.openenergymonitor.org/t/problems-creating-virtual-feed-after-update/10601
My PHP is not good enough to know why, but this change seems to work and it makes more sense to use the helper, get_engine I suggest.

Error evaluating engine number

---

core.php

This addresses issue #1135 where putting emoncms behind reverse proxy breaks the website. It is due to incorrect header (HTTP_X_FORWARDED_SERVER) being used to identify the real host URL. The correct header is HTTP_X_FORWARDED_HOST.

Corrected reverse proxy support

---

Modules/admin/admin_controller.php
Modules/feed/feed_controller.php
core.php
index.php

checked for the new constant at output
checked for the new constant when receiving controller response
added x-emoncms-message header on json errors
added not authenticated message to error log
used the new constant as the feed controller's default output
this doesn't relate to an issue. I'd noticed the string `#UNDEFINED#` being used in many places. just made one version of it.

defined string constant to check for when no route found

---

Modules/admin/admin_controller.php
core.php

fix #1269 
now using `rawurldecode()` to decode submitted special characters before user logs in.
also cleanly quit the current call using `exit()` once headers set by admin/setuser (not part of this issue  - noticed during testing)

decoded submitted special characters globally

---

Modules/user/user_controller.php

related to https://github.com/emoncms/graph/issues/83
user module endpoint `user/gettimezones` doesn't expose any personal information so doesn't require authentication before returning a value. removed the check for the `$session['read']` variable.

user/gettimezones doesn't require authentication

---

index.php

to use the functions within another part of the system (eg Module controller) I needed to modify the index.php to use the `include_once` and not the `include` statement to clear out errors in modules that also use these functions.

fix / added include_once to allow nav_functions.php to be used in controllers

---

Lib/misc/sidebar.js

this modification allows top-level menu items to act as links and not to just open/close the sidebar
related to demandshaper issue
https://github.com/emoncms/demandshaper/issues/14

enabled top nav items to behave like links

---

Theme/basic/theme.php

previously all the `<svg>` icons were in the `theme.php` file.
with this pull request the icons can be added within the `*_menu.php` file for each module and they'll be included into the `theme.php` in the correct place.

loading module specific icons in theme.php

---

Lib/misc/sidebar.css

issue was with the sidebar css overriding the `display` property. css now specific to `#sidebar` elements

fixed problem with bootstrap collapse not working

---

Modules/admin/pi-model.json

Updated pi-model.json with new rpi models, of course detect the new Raspberry Pi 4 too!
If you need it here is the generator: [https://github.com/gablau/rpi-revision-codes-utility](https://github.com/gablau/rpi-revision-codes-utility)

Updated pi-model.json with new rpi models

---

.travis.yml

Seems reasonable to make sure the PHP code (and other tests) are valid before trying to run browser tests which may be executing potentially broken code :)

Run composer test before browser tests

---

Modules/feed/Views/feedlist_view.php

the feed delete modal was incorrectly aligned
now looks like this:

fix feed delete modal layout

---

Modules/input/Views/input_view.js

fix #1286 
feeds and inputs list now remembers collapsed state across page loads

added cookie caching of input list state

---

.htaccess

fix #1220 
I've tested this on my laptop using the loopback network device... other systems may be different? 
Feedback of this pull request failing to restrict access to the `php-info.php` would be usefull (along with host machine details) *I'm testing on a dell laptop with ubuntu 18.04 running apache 2.4*
thanks @djh42 for the `.htaccess` code:
> https://community.openenergymonitor.org/t/installing-emoncms-redis-problem/10323/47
```
<Files php-info.php>
Require ip 10 172 192.168
</Files>
```
This requires any requests to `php-info.php` come from an IP address starting with:
```
- 10.❓.❓.❓
- 172.❓.❓.❓
- 192.168.❓.❓
```
this covers most local networks and local machine access.
As I'm on the local network and have one of the "whitelist" addresses I don't see the restriction. There might be …

added apache 2.4 access restriction to php-info.php

---

locale.php

fix #1243 
this is now how the language is selected for a user with this pull requeset...
*ORDER OF PREFERENCE FOR EMONCMS LANGUAGE SELECTION:*
1. non logged in users use the browser's language via `$_SERVER('HTTP_ACCEPT_LANGUAGE')`
2. logged in users use their saved language preference from mysql `emoncms.users.language`
3. logged in users without language saved uses `$default_language` from `settings.php`
4. else fallback is set to `en_GB`
If this isn't suitable we can discuss a preferred order of preference for language selection

clarified the default language selected

---

Modules/feed/engine/CassandraEngine.php
Modules/feed/engine/PHPFina.php
Modules/feed/engine/PHPTimeSeries.php
default.emonpi.settings.php
default.settings.php
process_settings.php

fix #1184 
Added `DATAPOINT_LIMIT` to `default.settings.php` & `default.emonpi.settings.php`
Replaced fixed value (`8928`) with `DATAPOINT_LIMIT` in **PHPFina.php**, **PHPTimeSeries.php** and **CassandraEngine.php**
[screenshot showing datapoint limit. limit has been incresed to 9999 in `settings.php`]

replaced hard coded limit for variable in settings.php

---

Modules/vis/vis_langjs.php
Modules/vis/vis_object.php
Modules/vis/visualisations/realtime.php
Modules/vis/widget/vis_render.js

added translation placeholder label "display as kw"
added default false in $visualisations array() vis_object.php
passed the $is_kw property to the realtime embed
divided data value by 1000 if $is_kw == true
fix #1394 
original issue was posted in the `dashboard` repository
related to emoncms/dashboard#230

added new option to realtime graph in dashboard

---

Theme/basic/embed.php

original issue was posted in the `app` repository.
related to https://github.com/emoncms/app/issues/95
I've "bumped" the css version to clear any cached stylesheets. I cannot re-produce the error as the "old" css has not been cached on my laptop
my screenshot has no data.. however you do see that the layout and text colours are correct:

bumped css version

---

Modules/admin/admin_main_view.php
Modules/admin/admin_model.php

fix #1364 
- removed 'hw' from `admin_model->get_rpi_info()`
- commented out the line in `admin_main_view()`
[screenshot of admin screen with raspberry pi's SoC removed]
> "...what might be useful is to have the RAM on a separate line..."
> @pb66, https://github.com/emoncms/emoncms/issues/1364
@pb66 - I haven't broken out the RAM from the RPi Model name as there is already a much more detailed Memory section in the admin view:
Please reply if you think the work is still required to split the lines by Model Name/Memory

removed rpi SoC from admin view

---

Modules/input/input_controller.php

fix #1406 
@pb66 @borpin 
I thought it was best to add the both api endpoints rather than removing the incorrectly set version.
so now both these api endpoints work:
- `input/get_inputs`
- `input/getinputs`

added api endpoint to match api documentation

---

Modules/admin/admin_controller.php
Modules/admin/admin_main_view.php

fix #1413 
only ran redis->info() once and reused the response
added python redis version
added php redis version
**needs some testing on other devices...**
...when running the command `pip show redis` via php the details are for all installed packages available to the `www-data` user. This works for my version as redis is installed system wide:
```
#> pip install redis --system
```
please let me know if your admin page (http://localhost/emoncms/admin/view) looks like this screenshot:
[screenshot of admin screen showing Redis component version numbers]

added redis versions

---

Modules/input/Views/input_view.js

related to #1424 
@borpin - I can't reproduce the error you reported... added an if statement to check that the variable is an array before the `push()` function is used
please let me know if the issue persists.

checked for type array to avoid error

---

Modules/admin/admin_controller.php
Modules/admin/admin_main_view.php

For systems without any RFM or serial interface, a 'none' firmware type is needed to make updates cleaner.
Ideally there would be a means of setting the firmware type.

Add 'none' to firmware type in admin

---

Modules/feed/feed_model.php

Correct setting typo from `csvdownloadlimit_mb` to `csv_downloadlimit_mb`.

Update feed_model.php - setting typo csv_downloadlimit_mb

---

Lib/misc/nav_functions.php

fix: #1475 
now uses the `asort()` `SORT_NATURAL` function to sort correctly.
also increments the number part of the sorted keys:
```
'a'=>'First Item',
'a1'=>'Second Item'
```
previously it would have shown an error when text keys were used as it couldn't increment the array's key to the next item.

fixed menu sort function to increment with number

---

process_settings.php

Update code to enable Envvars to be specified in the settings.ini
Needs testing!!!!!!
Discussion in #1452 refers

Enable envvars to be used

---

Modules/input/Views/input_view.js

swapped the time and value column widths.
fix #1481

corrected value column width.

---

Modules/input/Views/input_view.php

fix #1480 
fixed this issue using CSS style sheet

stopped input name from overflowing to next line using CSS

---

Modules/user/user_controller.php

encoded url parameter as html special characters before using it as a value in the referrer input field
used php's [htmlentities()](https://www.php.net/manual/en/function.htmlentities.php) function to clean the value. eg: `<html>` to `&lt;html&gt;`
The input value is used to redirect the user on successful login.
The value was displayed as "raw" html and was able to be altered as such in the url:
```html
<input name="referrer" type="hidden" value="<?php echo $referrer ?>">
```
https://github.com/emoncms/emoncms/blob/master/Modules/user/login_block.php#L105
the `$referrer` var is passed to the login page as a url encoded base64 string and is only decoded and displayed on the login page.

formatted url param as html characters

---

index.php

Please stop logging invalid keys in case someone accidentally provides one that is valid for another service.

Stop logging failed keys

---

Modules/feed/feed_model.php

fix #1529 
using php filter_var() function to remove unwanted characters. will still allow most desired characters.

using filter_var() to sanitize user input for feed units

---

Modules/admin/admin_model.php

fix #1528
the reboot/restart buttons are currently set to show if ran on a raspberry pi. the [is_Pi()](https://github.com/emoncms/emoncms/blob/master/Modules/admin/admin_model.php#L232) function checks the device's mac address starts with the range associated to the raspberry pi foundation.
**NOT TESTED ON RASPBERRY PI 4**
added new mac address range for rpi4.
does the raspberry pi 4 has a different mac address range?? please comment if you know.
If you run this on your raspberry pi4 you should get your mac address for the ethernet and wifi network controllers...
```
ip address | egrep "^\s+link" | awk '{$1=$1};1' | cut -d' ' -f2 | tail -n+2
```
> this command will list the mac addresses on your raspberry pi
> _(steps: find all lines starting with 'link', trim white space chars, display …

is_Pi() function MAC address range

---

Modules/feed/Views/feedlist_view.php

When user is deleting an empty feed, browser shows JS error.
This pull request suggest a fix for that error

FIX: JS error on deleting empty feed

---

Lib/dbschemasetup.php

too much confusion in pull #1484. separated to 2 pull requests. this is the second..
related #1484 
checked field type when comparing
wrapped table name in quotes
was having errors when updating a schema. these checks are useful if databases are named with a reserved word
also the schema wasn't updated when the field types were changed.

separated from #1484

---

locale.php

A look at blame shows there has been an else in here since it was created, but it hasn't done anything in the function in all that time. It's a case of create an else case or remove it.

remove empty else from the function

---

Lib/misc/sidebar.css
Modules/admin/admin_menu.php

Side bar divider is shown as a clickable empty menu item navigating to `+` causing page reload. Such behaviour may confuse the user. This pull request makes the divider visually distinct and non-clickable. Also its href is changed to `#` so that even it is clickable it would not reload the page.

FIX: sidebar divider made unclickable and with href=#

---

Modules/input/input_model.php

In some cases, when REDIS is disabled, cleaning a process list may endup with a PHP error. This pull request suggest a fix for that.

FIX: PHP error caused by disabled REDIS

---

Modules/feed/feed_controller.php

When user deletes a feed and then open a previously saved graph, the `graph` module shows improper message and stalls with a broken graph with no ability to fix it. This PR fixes PHP error (improper collection of feed ids) and and suggest a solution for broken graphs by returning an array of missing feed ids. This will let the client (`graph` module) to remove bad feeds from the graph and keep good ones.

FIX: handling of missing feeds

---

process_settings.php

Added serif to font-family:arial; as its missing a generic-family - options from one of the following: "serif", "sans-serif", "cursive", "fantasy", "monospace".

added missing generic-family to font name

---

locale.php

The following warning is generated when php = 7.4
<b>Warning:</b>
Use of undefined constant LC_MESSAGES - assumed 'LC_MESSAGES' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\emoncms\locale.php on line <b>108</b>

Clear warning when hosted on php7.4

---

Modules/feed/Views/feedlist_view.php

error in the css postion isn't valid.
To see ignored attribute goto feeds create a new virtual feed then select delete. In the modal that pops up head to modal-footer > feeds-to-delete

spelling error

---

Modules/admin/admin_model.php

When viewing the Pi information in Admin the display of information is bold for the titles and normal for the information except for the read-write state. This sets the read-write/read-only value the same as all the other information.

admin model is applying formatting for file state

---

Modules/admin/admin_main_view.php

Currently the temp values are given as `Temperature: 48.31°C - 44.31°C` but doesnt give any indication to what the temps are for.
This PR splits them up and labels them to show what the end user is looking at.
`CPU Temperature 47.77°C`
`GPU Temperature 46.41°C`

Split the Temp Values to display what they are

---

Modules/process/process_processlist.php

This resolves an issue I found where the rate of change process doesn't pass on its value to the next step - it seems for some reason the return was commented out.

Fix rate of change process

---

scripts/services/emoncms_mqtt/emoncms_mqtt.php

#1612 
A MQTT message topic & payload such as 
`/emon/emontx001/0/Pulse 10`
and  
`/emon/emontx001/0 {"Pulse":10}` 
will now both appear under the Node `emontx001` as `0_Pulse`.

Fix for multi level topics and JSON Payload *Breaking Change*

---

scripts/services/install-service-runner-update.md
scripts/services/service-runner/service-runner.py
scripts/services/service-runner/service-runner.service

Port service-runner to python3.
- Change indentation to 4 spaces to conform with the rest of the
project.
- Utilise redis' blpop method to block until there is something to do,
instead of spinning with a short sleep.
- There was a lot of code fighting against itself, like signal handlers
which didn't do any cleanup, other than printing a message, which
complicated the main loop. Since the program is running under a service
supervisor (presumably systemd) this is unnecessary, so remove it.
- Utilise the print(..., flush=True) syntax.
- Avoid subprocess.call(..., shell=True). The command lines are so
simple that we can (and already do) parse them ourselves.
- Avoid wrapping too much code in a try/except. There is only one call
to redis and therefore only one place where the connection can …

Update service-runner to python3.

---

Modules/input/Views/input_api.php

This fixes Issue #1621 by URL encoding the Input API example
which uses a text string for the date and time. The date
format used includes the current system timezone which
contains a "+" character which, if not URL encoded, will be
interpreted as a space. This causes a failure in the time
parsing.
The link in the live example will now behave correctly when clicked.

Fix URL Encoding of Input API example with time to close #1621

---

Modules/admin/admin_main_view.php

Admin page MySQL server info area was displaying Redis host as MySQL
host.  This changes the key read from $system from 'redis_server' and
'redis_ip' to 'db_server' and 'db_ip'.

Fixes #1640

---

Modules/input/input_methods.php

*Breaking change for anyone logging time*
re #1624 
Remove the time element from the array so no Input is created.
If the time is a string, then a N/A appears in the Inputs
If a user wants to log time it can be added as an additional JSON field but not called `time`.

Remove Time from input array

---

Modules/process/process_processlist.php

Fix for bug were null values in either source feeds being used in a virtual feed process were converted to zeros in the output as seen in the graph.
@chaveiro

virtual feed null value fix

---

Modules/input/input_methods.php

Remove `unset($jsondataLC['time']);` as it was causing unexpect results
https://community.openenergymonitor.org/t/anyone-importing-data-from-weewx-weather-station-into-emoncms-its-stopped-working/16916/2

Remove Unset of time parameter

---

locale.php

Resolves #1680 
Tested against the emoncms hassio image.
https://github.com/inverse/hassio-addon-emoncms/issues/16#issuecomment-819750768
That warning is no-longer present. The others I'll still need to figure out though.

Define GLOB_BRACE if non-existent

---

Modules/admin/admin_controller.php
Modules/admin/admin_model.php
Modules/admin/static/admin_styles.css

The Admin page did not handle a situation where a service was loaded in systemd but purposefully masked so it wouldn't run (for example, when running the MQTT broker on another machine).  Masked services were reported as errors since they weren't running, whether they were supposed to or not.  Such services are now displayed in a new 'Masked' state with a grey status badge (instead of the original red/green badges).
See further discussion of this change at https://community.openenergymonitor.org/t/admin-page-services-status-doesnt-handle-disabled-services/15793/2

Admin display of masked services

---

locale.php

My attempt to fix this in #1685 didn't work and only hid the problem. This solution removes the need for the glob brace expansion by calling glob multiple times.
Tested on the addon on a branch and it works.
p.s. with pull requests when you use squash instead of merge the git history of the repo looks cleaner as you remove all the noise within the PR itself :)

Work around lack of GLOB_BRACE properly 

---

default-settings.ini
default-settings.php
scripts/services/emoncms_mqtt/emoncms_mqtt.php

This pull request adds support for multi user mqtt environments where data is posted in mqtt messages of format:
basetopic/userid/nodeid
The single user default is:
basetopic/nodeid
Multi user mode is enabled from settings.ini by adding the following setting under the mqtt section:
multiuser = true

support for multi user mqtt environment

---

Modules/user/rememberme_model.php
Modules/user/user_model.php
core.php

Protect against Cross-Site Request Forgery by restricting use of session cookie to emoncms domain

secure session cookie, use samesite=strict

---

Modules/feed/engine/CassandraEngine.php
Modules/feed/engine/PHPFina.php
Modules/feed/engine/PHPFinaTest.php
Modules/feed/engine/PHPTimeSeries.php
Modules/feed/engine/RedisBuffer.php
Modules/feed/engine/TemplateEngine.php
Modules/feed/engine/VirtualFeed.php
Modules/feed/engine/shared_helper.php
Modules/feed/feed_controller.php
Modules/feed/feed_model.php
Modules/process/process_processlist.php

Part of work on https://github.com/emoncms/emoncms/issues/1744
use get_data_combined directly in feed_model, remove get_data_DMY, get_average & get_average_DMY methods

use get_data_combined directly in feed_model

---

Modules/feed/engine/CassandraEngine.php
Modules/feed/engine/MysqlTimeSeries.php
Modules/feed/engine/PHPFina.php
Modules/feed/engine/PHPTimeSeries.php
Modules/feed/engine/RedisBuffer.php
Modules/feed/engine/TemplateEngine.php
Modules/feed/engine/VirtualFeed.php
Modules/feed/feed_controller.php
Modules/feed/feed_model.php
Modules/vis/visualisations/editrealtime.php

This pull request expands support for different time formats when making get_data requests.
Examples:
feed/data.json?ids=1&start=-2 week&end=-1 week&interval=daily
feed/data.json?ids=1&start=-2 week&end=-1 week&interval=daily&timeformat=unix
feed/data.json?ids=1&start=-2 week&end=-1 week&interval=daily&timeformat=excel
feed/data.json?ids=1&start=-2 week&end=-1 week&interval=daily&timeformat=iso8601
Example of data returned in iso8601 format:
```
[
{
"feedid": "1",
"data": [
[
"2021-11-19T00:00:00+00:00",
49
],
[
"2021-11-20T00:00:00+00:00",
47
],
[
"2021-11-21T00:00:00+00:00",
161
],
[
"2021-11-22T00:00:00+00:00",
46
],
[
"2021-11-23T00:00:00+00:00",
507
],
[
"2021-11-24T00:00:00+00:00",
null
],
[
"2021-11-25T00:00:00+00:00",
null
],
[
"2021-11-26T00:00:00+00:00",
null
]
]
}
]
```

wider timeformat support both for request params and returned data

---

Modules/feed/Views/feedlist_view.php
Modules/feed/engine/MysqlTimeSeries.php
Modules/feed/feed_model.php

This pull request is easier to understand changes by looking at each commit in turn. 
- The main goal was to update the engine to match the data request response formats of the other engines.
- I've done this by reusing and not changing the sql previously used.
- The only method that is a little slower is the standard get_data without averaging method as this uses the 'data_sampling' option as standard (it could change to a faster return all datapoints approach as the interval approaches the interval of the data stored in the feed, but needs to return timestamps in relation to request)
- The return original interval option needs to be reintroduced as well (same as for phptimeseries)
- csv export method has been integrated in the other get_data methods 
PHPFina vs Mysql data response …

Mysqltimeseries update

---

Modules/admin/admin_model.php
Modules/admin/pi-model.json

Added the two missing mac address ranges for raspberry pi detection
Listed here https://udger.com/resources/mac-address-vendor-detail?name=raspberry_pi_foundation
Added the missing revision info for Pi4B v1.5 2GB
Listed here https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/computers/raspberry-pi/revision-codes.adoc

Add Pi mac addresses and version info for Pi 4 v1.5 detection

---

Lib/EmonLogger.php
Modules/user/user_controller.php
Modules/vis/vis_controller.php
core.php
locale.php
route.php

Changes have been done to : 
route.php
locale.php
core.php
user_controller.php
test if variables are defined to null before calling functions using those variables as parameters (Passing null to parameter #1 ($string) of type string is deprecated in php 8.1)
replace  FILTER_SANITIZE_STRING with htmlspecialchars() (Constant FILTER_SANITIZE_STRING is deprecated )

Php 8.1 fix   part1

---

Modules/feed/feed_controller.php

* This occurs using PHP 8.1 when the returned JSON begins with: *
* <br />
* <b>Deprecated</b>:  Automatic conversion of false to array is deprecated in
* <b>/var/www/emoncms/Modules/feed/feed_controller.php</b> on line <b>94</b>
* <br /> *

Fix false to array deprecation in feed/fetch.json

---

scripts/services/emoncms_mqtt/emoncms_mqtt.php

Add some changes to check the existence of certpath, keypath and keypw before usng them in setTlsCertificates
Fix #1835

Fix using using SSL with MQTT without client certificate

---

Modules/admin/admin_model.php
process_settings.php
scripts/emoncms-cli

Found that these deprecated string interpolations tend to cause some rather scary looking errors re:headers output when running on PHP 8.2, and didn't think it would harm anyone still running on PHP7.

Fix deprecation warnings from PHP8+

---

Lib/vis.helper.js

Fix timepicker not working on all modules except graph.
Please don't change global function names that affect other modules without testing.  
The original function name used across emoncms vis and tables date time picker is *parse_timepicker_time* not *parseTimepickerTime*. Made this work for all but please correct the graph module to use the correct (historic) function name.

Fix timepicker not working outside graph module 

---

Modules/feed/feed_model.php
Modules/user/user_controller.php

Another set of issues from deprecations I stumbled upon while running my own instance of Emoncms on PHP 8.2 -- seems `FILTER_SANITIZE_STRING` was ambiguous and it is thus frowned upon from using it now, `htmlspecialchars()` seems to be the best replacement for most instances.
There was one other instance of `FILTER_SANITIZE_STRING` in the codebase, but it seemed to be far more complicated than these cases - multiple other flags were likely passed to `filter_var` and thus, I wasn't confident `htmlspecialchars()` was a drop-in replacement.
I was able to test the user controller change on my instance (its in the logout action), but I don't have any feed data just yet, so I'm flying a bit blind there.

Remove deprecated FILTER_SANITIZE_STRING in feed_model and user_controller

---

scripts/phpmqtt_input.php
scripts/services/emoncms_mqtt/emoncms_mqtt.php

Prevent use of Redis for obtaining data to publish to MQTT when Redis is not enabled
Also, add comments to phpmqtt_input.php to indicate that it is deprecated in favour of emoncms_mqtt.php

Fix failure in MQTT import when Redis is not enabled

---

Modules/admin/Views/update_view.php

Issue https://github.com/emoncms/emoncms/issues/1815 and https://github.com/emoncms/emoncms/issues/1806 highlight that the update window disappears within 3 seconds of the update completing.
Curiously, this window remains permanently visible if the update log doesn't exist.
I've removed the 3 second timer which triggers hiding the window

Keep update log visible

---

Modules/feed/feed.js
version.json

Required to https://github.com/emoncms/dashboard/pull/284

Add support for feed.getvalue asyncronously

---

Modules/admin/admin_model.php

fix emoncms_1  | df: unrecognized option: block-size=1 when running emoncms on alpine.

Use more common -B for specifyng block size for df

---

Lib/responsive-linked-tables.js
Lib/tablejs/custom-table-fields.js
Modules/feed/Views/feedlist_view.php
Modules/input/Views/input_view.js
Modules/input/Views/input_view.php
Modules/process/Views/process_ui.js
version.json

- Fix report of last updated input and feed.
- Refactor to use same logic for both in resposive-linked-tables.js shared lib.
- Added new feature to report month/day of last update time when update was more than 1 month ago in gray color. Useful for easy understanding time for disabled inputs or feeds.
- Fix consider server time out of sync with timeServerLocalOffset var.
- Fix input table first line offset.
Screenshot:

Fix last update time for inputs and feeds

---

Modules/admin/admin_model.php

Under 01Feb-24 versions of EmonSD, the serial and model information fail to parse 
for current RPi models. This PR adjusts the match logic to be a bit more flexible 
in how the regex gets assigned. Tested locally on a RPi4B.

Adjust how serial, revision, and hardware are parsed out.

---

Modules/admin/Views/admin_main_view.php
Modules/admin/admin_model.php

This commits permits the admin module to work friendly in container without having to deal with systemctl commands or df, iostat or grep options (-x squashfs, -o JSON, -oP) that it cannot achieve
Still in containers, this also permits the sync module not to complain not to find emoncms_sync

Adapt admin model for a correct behaviour in container

---

Modules/admin/admin_model.php

when using the original openenergymonitor/emoncms container :
1) it is better not test the existence of workers, so getServiceStatus has to return an empty array
2) /data folder does not exist, it is OK to use the original disk_list method as it works well on Debian (which was not the case on Alpine)

Readjust admin model to work with BOTH standalone & original containers

---

Lib/process_old_settings.php

I found that these two settings are critical for MQTT support in EmonCMS, but if running on a legacy config format, they don't exist.
* userid
* multiuser
I don't believe these are used in a local installation, so have defaulted them to 1, and false respectively.

Add missing MQTT settings for old config

---

.htaccess

When exporting large feed, the request timeout after default value of 30secs.  This update extend the maximum execution time to 300secs

Update .htaccess so that export can take more than 30secs

---

scripts/services/emoncms_mqtt/emoncms_mqtt.php

Publish 5 minute mqtt msg process count to mqtt so can be seen as input in emoncms
This allows users to easily see performance and any variances in mqtt volume. Also changed the log level for this to WARN so it can easily be seen in the logfile without drowning in debug data.
This is a very useful stat to see (and log optionally log as a feed) and helped me debug several problems with my installation (run away rfm69 module for example).

Publish 5 minute mqtt msg process count to MQTT 

---

scripts/services/emoncms_mqtt/emoncms_mqtt.php

JSON values from ebusd are published on MQTT with values "boxed" in a
format like: { name: xxx, value: xxx }
Support this structure by allowing deeper-nested JSON structures, and
unpacking the value and adding the name if present.
Ensure non-scalar values (nested JSON, etc) are not recorded, or logged
without being converted back to JSON.

mqtt: support nested JSON values

---

.devcontainer/dev-compose.yaml
.devcontainer/devcontainer.json
.devcontainer/setup.sh

this is to introduce a development process using vscode and devcontainer
- git clone your emoncms fork on you development machine
- launch vscode
- open your emoncms fork in vscode and reopen in container > emoncms should be accessible locally on port 8088
module per module, you can adapt the url repo once you have a fork of the considered module. Adaptation has to be done in the .devcontainer/setup.sh file. Once adapted, press ctrl+shift+P and rebuild

Add .devcontainer to simplify development
